### ISSUE TITLE
reduce number of things we build

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#12]
I think we should save ourselves some time by disabling some options (like we did for STIR)

HDF5:
-	HDF5_BUILD_EXAMPLES=OFF
-	HDF5_BUILD_HL_LIB=OFF (to be tested)
-	HDF5_BUILD_TOOLS=OFF (or are these useful?)

Gadgetron:
-	Do we need Python gadgets? If not, we don’t need boost_python.
-	Do we need Gadgetron’s MATLAB support?

**Comment by DANAJK** [comment]
For v0.9 we don't need Python gadgets or the Gadgetron MATLAB support. However, one of SIRFs strengths may turn out to be that it becomes an easy way to install Gadgetron and it is of particular appeal to users who like to use Python or MATLAB interfaces, hence, providing this 'service' could increase the appeal of SIRF.

I don't remember ever having to worry about single or double precision for fftw in the past when building ISMRMRD or Gadgetron, so I am not sure why that has become a problem.

On 23 Apr 2017, at 10:54, Kris Thielemans <notifications@github.com<mailto:notifications@github.com>> wrote:


I think we should save ourselves some time by disabling some options (like we did for STIR)

HDF5:

  *   HDF5_BUILD_EXAMPLES=OFF
  *   HDF5_BUILD_HL_LIB=OFF (to be tested)
  *   HDF5_BUILD_TOOLS=OFF (or are these useful?)

Gadgetron:

  *   Do we need Python gadgets? If not, we don’t need boost_python.
  *   Do we need Gadgetron’s MATLAB support?

**Comment by KrisThielemans** [comment]
boost-python is currently required after all #15

**Comment by KrisThielemans** [comment]
As mentioned in #15, we currently switch Gadgetron's Python and Matlab support off. That saves us compilation/compatibility headaches. If we want to enable this later, then we'd have to introduce CMake variable like `Gadgetron_BUILD_PYTHON_GADGETS`. However, then we also need to be able to tell the boost dependency that we do need boost-python (see #5), but that's probably not trivial.

**Comment by KrisThielemans** [comment]
#64 reduced HDF5 build as suggested above. Need to introduce CMake options to enable them.

**Comment by KrisThielemans** [comment]
@paskino, this seems a trivial thing to do, but it isn't really necessary. Therefore feel free to re-assign to v2.1

**Comment by KrisThielemans** [comment]
let's just create 2 new options and modify https://github.com/CCPPETMR/SIRF-SuperBuild/blob/7870f68b7d11c934d908516ff088527659f1cbc4/SuperBuild/External_HDF5.cmake#L83-L84

**Comment by KrisThielemans** [comment]
> 

I think this is the only thing that was pending here, but as nobody ever asked for it, I will close this issue
