### ISSUE TITLE
need to configure input files for Windows

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#128]
the Superbuild needs to create a powershell and bit file (when on Windows) like the current shell configuration files, based on following
```
$Env:Path += ";C:\Users\krisf\Documents\devel\build-VC\SIRF-SuperBuild-CMAKE3.11\INSTALL\bin"
 $Env:Path += ";C:\Users\krisf\Documents\devel\build-VC\SIRF-SuperBuild-CMAKE3.11\INSTALL\FFTW"
 $Env:Path += ";c:/Users/krisf/Documents/devel/boost_1_63_0/lib64-msvc-14.0/"
 $Env:PYTHONPATH = "C:\Users\krisf\Documents\devel\build-VC\SIRF-SuperBuild-CMAKE3.11\INSTALL\python"
 $Env:MATLABPATH = "C:\Users\krisf\Documents\devel\build-VC\SIRF-SuperBuild-CMAKE3.11\INSTALL\matlab"
 # need to be forward slashes 
 $Env:SIRF_PATH = "C:/Users/krisf/Documents/devel/build-VC/SIRF-SuperBuild-CMAKE3.11/sources/SIRF"
```

**Comment by evgueni-ovtchinnikov** [comment]
I have cloned and built SIRF-SuperBuild (using CMake 3.10.0) on Windows 7 with Visual Studio 2013.

Had a problem with missing files debug.lib and optimized.lib. Figured out they are not actually needed - on the internet people suggest deleting them from the project,  but it did not work for me as Build starts by running CMake, which creates them again – so tricked the Build by copying another .lib file and renaming the copy into debug.lib and another copy into optimized.lib.

This worked, and I set $Env:PYTHONPATH to new path in powershell, and was able to run PET tests.

Some progress then.

By the way, CMake left Python and Matlab destinations empty after Configure, so I set them manually – was it actually needed?

**Comment by KrisThielemans** [comment]
great. I belief that the `debug.log` and `optimized.lib` are a VS 2013 issue. I certainly don't have it with 2015.

could you try the matlab side as well? Should work...

I'm also very interested in seeing if you can run the MR code (by usin gth eVM an dport forwarding of course). that's the bit that failed for me.

**Comment by evgueni-ovtchinnikov** [comment]
python can run mr demos ok

matlab works for both pet and mr demos when started from windows; from git shell (with -nodesktop) it works too if i do not set $Env:MATLABPATH  as you suggested, otherwise i get "Undefined function or variable 'matlabrc'", and mutilities library fails to load

**Comment by KrisThielemans** [comment]
Excellent news!

From [here](https://uk.mathworks.com/matlabcentral/answers/96935-why-do-i-get-an-undefined-function-or-variable-matlabrc-error-and-loss-of-command-functionality-w) it looks like we should add `$matlabroot\toolbox\local` (obviously with `$matlabroot` filled in). Can you try that?

 This should be doable from CMake as we'll know what `MATLABROOT` is I believe.

**Comment by evgueni-ovtchinnikov** [comment]
i mean it works now that i added `$matlabroot\toolbox\local` to `$Env:MATLABPATH`

**Comment by KrisThielemans** [comment]
Largely a duplicate of #460. @evgueni-ovtchinnikov is there anything here that needs to be handled?

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans nothing springs to mind at the moment

**Comment by KrisThielemans** [comment]
closing as duplicate
