### ISSUE TITLE
HDF5 conflicts

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#129]
we're getting conflicts between HDF5 versions. Easiest route might be to use static linking  when building SIRF and ISMRMRD.

**Comment by KrisThielemans** [comment]
confirmed with @johannesmayer that HDF5 conflicts easily happen even on the VM. We had the system HDF5, the SuperBuild HDF5 and ITK comes with HDF5 as well. Matlab does as well. All different versions. And the GE

HDF5 library has a habit of causing segfaults when there's a version mismatch anywhere, so this needs to be avoided.

I lean now towards relying on a system HDF5 by default (i.e. to not make the situation worse), and introduce static linking. The latter should be doable by adding `-DHDF5_USE_STATIC_LIBRARIES=ON` in the `External*cmake`. I don't think I'd put it in SIRF's CMakeLists.txt.

Anyone any other opinions? @bathomas, @casperdcl ?

**Comment by paskino** [comment]
Can't we rely only on the one we build?

**Comment by KrisThielemans** [comment]
we're trying to, but failing :-; I did notice there were a few `HDF5_LIBRARIES` missing in the `External*` files. @johannesmayer, maybe you could generate a PR with those fixes to the SuperBuild. However, even then we had conflicts until we deleted all our own HDF5 files, and just relied on the system one. I now think that relying on the system one is best, unless we cannot (e.g. because it's too old).

**Comment by KrisThielemans** [comment]
check if ITK can be build with a specific HDF5.

change option `USE_SYSTEM_HDF5` depending on `find_package`

**Comment by KrisThielemans** [comment]
> check if ITK can be build with a specific HDF5.
yes: `-DITK_USE_SYSTEM_HDF5=ON`

**Comment by KrisThielemans** [comment]
The situation on specifying HDF5 location is actually complicated.

At present we set `HDF5_ROOT`, `HDF5_INCLUDE_DIRS` and most of the time `HDF5_LIBRARIES`.  However, if `USE_SYSTEM_HDF5=OFF`, `HDF5_LIBRARIES` is actually empty.

According to the [`FindHDF5` doc](https://cmake.org/cmake/help/latest/module/FindHDF5.html), only `HDF5_ROOT` should be used and the others will be ignored. However, with CMake 3.7.2, setting the others actually prepends them to the final version seen after `find_package(HDF5)`, therefore taking precedence (which I guess is good, although unnecessary). I think with more recent CMake, those variables might be ignored, but I haven't checked properly.

Because of all this, I suggest removing the explicit setting of `HDF5_INCLUDE_DIRS` and `HDF5_LIBRARIES`.

However, this seems to mean that with current master, we do set `HDF5_ROOT` everywhere ok, except for ITK. But ITK by default builds its own HDF5, which one would hope doesn't conflict with anything else (libraries are called differently, e.g. `libitkhdf5.a`, and include files should only be found when using `itkhdf5/hdf5.h` etc). I haven't been able yet to let anything in SIRF depend on an itkhdf5 library.

All in all, it's a mistery why @johannesmayer had HDF5 conflicts, and that's of course worrying (as it means I don't know how to fix it).

@johannesmayer, do you remember what depended on the itkhdf5 library?

**Comment by KrisThielemans** [comment]
this seems largely obsolete. We still have some HDF5 problems, but there is likely no tmuch here that is relevant.
