### ISSUE TITLE
building gadgetron on VM with boost 1.68 causes undefined reference to `boost::system::detail::generic_category_instance'

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF-SuperBuild#161]
Building Gadgetron needs gcc6 and boost 1.65.0 We tried with 1.68.0, but then got
```
undefined reference to `boost::system::detail::generic_category_instance'
```
This might be related to https://github.com/boostorg/system/issues/26 as g++-6 defaults to C++-14 and therefore resolved by making sure that boost is built with gcc-6. This is actually #14.

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov please try again with the new versiono fthe Superbuild. It works for me.

**Comment by evgueni-ovtchinnikov** [comment]
`update_VM.sh` runs gcc-5.4.0

linking executable test_ismrmrd failed with error messages

    undefined reference to `boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
    undefined reference to `boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'

had to use the same trick of setting (after failed update) `USE_SYSTEM_ISMRMRD=ON` to build

**Comment by KrisThielemans** [comment]
Confirmed that this also happens with gcc 5.4 and older Gadgetron, e.g. https://github.com/gadgetron/gadgetron/commit/e7eb430673eb3272e8a821b51750c0a2a96dafed

It disappears when editing gadgetron's [CMakeLists.txt](https://github.com/gadgetron/gadgetron/blob/e7eb430673eb3272e8a821b51750c0a2a96dafed/CMakeLists.txt#L145) to force use `std=c++11` and not 14 (although this gives some warnings)

It seems therefore that we cannot use a packaged system boost 1.68, and that we'd have to build Boost ourselves, making sure that c++-14 is used.

sigh.

**Comment by KrisThielemans** [comment]
Lengthy discussion at https://groups.google.com/forum/#!topic/boost-developers-archive/EWG5NVOZo_g Conclusion is that you need to build boost (or any C++ library) with the same C++ standard version as you own code.

This seems to imply that we need to figure out what compiler options Gadgetron used, and then always build boost ourselves, using e.g. `cxxstd=14`.

Note that boost.system is header-only from [1.69](https://www.boost.org/users/history/version_1_69_0.html), which might help a bit (but could still throw up problems for other boost libraries)

**Comment by KrisThielemans** [comment]
Current Gadgetron master [attempts to use C++ 20](https://github.com/gadgetron/gadgetron/blob/b74270142683cb461292e7714f1755969a5bbccf/CMakeLists.txt#L158) (CMake will downgrade if it is not supported by the compiler)
