### ISSUE TITLE
Update SIRF-SuperBuild version_config to know if STIR has been built with ITK

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF-SuperBuild#199]
_Originally posted by @KrisThielemans in https://github.com/CCPPETMR/SIRF/issues/294#issuecomment-455208148_

**Comment by rijobro** [comment]
If we now point to STIR 4, alpha release then I guess this can be closed, right?

**Comment by KrisThielemans** [comment]
you know better than me ! feel free to do so
