### ISSUE TITLE
dependent projects need to be passed variables as cached

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#203]
We currently pass lots of directories like this
```cmake
... -DSTIR_DIR=${STIR_DIR} ...
```
This works fine. However, if you then go into the build directory of the dependent project (e.g. SIRF), and issue CMake there, it appears as if `STIR_DIR` is not set as part of the cached variables. I believe this therefore can cause problems because it might then pick up another location (only 99% sure).

The solution seems to be to do
```cmake
... -DSTIR_DIR:PATH=${STIR_DIR} ...
```
then it becomes a cached variable. Aside from less error-prone, I think it's also more user friendly. Of course, this would mean changing quite a lot of these.

Any objections?

**Comment by KrisThielemans** [comment]
@rijobro can you check if adding `PATH` indeed caches it?

**Comment by rijobro** [comment]
Confirmed. We should be doing this.

**Comment by paskino** [comment]
Is **all** variables or just the paths? I presume it's all.

**Comment by KrisThielemans** [comment]
All, indeed
