### ISSUE TITLE
Add Travis test for using Gadgetron via Docker

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#206]
As opposed to building Gadgetron, we can use its docker container. This was tried by @rijobro to fix #193. That attempt was abandoned as Travis doesn't support Docker on OSX, but we should add a test case on Linux. We should then also document how to do this (obviously by pointing to the Gadgetron doc).

**Comment by casperdcl** [comment]
https://github.com/CCPPETMR/SIRF-SuperBuild/pull/214/commits/3fff29474f05338e7b265e947363ceebe6da0e6d is initial framework

**Comment by casperdcl** [comment]
@KrisThielemans @evgueni-ovtchinnikov is there an env variable for pointing to the gadgetron host? My assumption is this is the workflow:

- [x] `sirf` container: `-DBUILD_GADGETRON=OFF`
- [x] `gadgetron` container: expose `9002`
- [ ] `sirf` container: ensure use of `tcp://gadgetron:9002` via either an env var or confic file etc.
  - I assume the current default is `tcp://localhost:9002`, in which case port forwarding might also be an option

**Comment by casperdcl** [comment]
should be noted that the current `ccppetmr/sirf` image (building gadgetron) is 3.5GB, while `gadgetron/ubuntu_1804_no_cuda` alone is 3.74GB on my machine (must contain more optional features than we build)

**Comment by KrisThielemans** [comment]
Currently host and port are [hardwired](https://github.com/CCPPETMR/SIRF/blob/0bd5123952e070aa52f43a458dcfd8705f23e5b2/src/xGadgetron/cGadgetron/include/sirf/cGadgetron/gadgetron_x.h#L236), see https://github.com/CCPPETMR/SIRF/issues/182

**Comment by casperdcl** [comment]
after #214 is merged I'll have a wonderfully small change to make to spin off a separate `gadgetron` container and avoid building it in the `sirf` one.

The downside is that the only way hardcoded `localhost:9002` can work with docker networking restrictions on port forwarding is on linux. Need to remove hardcoded `localhost` to work on windows.

**Comment by casperdcl** [comment]
> `- sirf` container: ensure use of `tcp://gadgetron:9002` via either an env var or config file etc.
>    * I assume the current default is `tcp://localhost:9002`, in which case port forwarding might also be an option

@evgueni-ovtchinnikov @KrisThielemans is this now done?

**Comment by KrisThielemans** [comment]
I think so, but I'm not sure how. Have a look at https://github.com/CCPPETMR/SIRF/issues/182

**Comment by casperdcl** [comment]
right...

https://github.com/CCPPETMR/SIRF/blob/4b5f9ff429f64f8ae878c1366ab0cf2805526e72/examples/Python/MR/Gadgetron/fully_sampled_recon_single_chain.py#L97-L111

So we can do this in python then:

```python
recon.set_host(os.environ.get('GADGETRON_HOST', 'localhost'))
recon.set_port(os.environ.get('GADGETRON_PORT', '9002'))
```

**Comment by KrisThielemans** [comment]
Obsolete as we're not using  Travis. Even for GHA it doesn't seem to be a great thing to do as  Gadgetron now distributes via conda
