### ISSUE TITLE
Matlab uses a different version of boost compared to SIRF

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF-SuperBuild#207]
I'm trying to get SIRF installed on the remote desktop to the university. This means that we don't have complete control over installed packages etc.

I installed SIRF using a version of boost that we installed ourselves (`/slms/inm/research/tools/TL/lib/libboost_[component].so.1.68.0`). However, Matlab is using its own version of boost (`/cs/sys/software2/Matlab/matlab-R2016b/bin/glnxa64/libboost_[component].so.1.56.0`). This causes matlab to crash as I try to load the SIRF libraries and the ctests fail accordingly.

I gave the following a go: `cmake --DCMAKE_MODULE_LINKER_FLAGS=-Wl,--exclude-libs,ALL`, which I got from [here](https://cmake.org/cmake/help/v3.3/module/FindMatlab.html), but no luck.

Anyone got any expierence or ideas?

**Comment by KrisThielemans** [comment]
>     * Gadgetron currently requires 1.64.0. I've asked them about Matlab issues

They experience the same troubles.

**Comment by KrisThielemans** [comment]
Info from MathWorks:

> The BOOST libraries that MATLAB internally uses are as follows:
> MATLAB R2016a - R2017b            Boost library version 1.56.
> MATLAB R2014a to R2015b          Boost library version is 1.49
> From MATLAB R2018a, our development team has eliminated the compatibility restrictions for the Boost C++ Library.

**Comment by KrisThielemans** [comment]
closing as only applies to old MATLAB
