### ISSUE TITLE
build less of ITK

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#210]
In the spirit of #12, and because of time-outs on Travis https://github.com/CCPPETMR/SIRF/issues/286, we should try to reduce what modules are built from ITK, which [can be done via groups](https://itk.org/ITKSoftwareGuide/html/Book1/ITKSoftwareGuide-Book1ch2.html). I think STIR only needs `-DITKGroup_IO=On`.

Currently, we're building with `-DModule_ITKReview=ON`, which then drags in pretty much everything. This is currently [required for pet-rd-tools[(https://github.com/UCL/pet-rd-tools/issues/35). Until that is fixed, we could presumably only include that module if we're building pet-rd-tools, but that gets a bit messy.

**Comment by bathomas** [comment]
[pet-rd-tools](https://github.com/UCL/pet-rd-tools) no longer requires `Module_ITKReview`. See #211

**Comment by paskino** [comment]
By the way, I noticed that editing the cache and rebuilding would always trigger the build of ITK. Even if I've not changed the ITK config/files.
