### ISSUE TITLE
Travis not to do MR_TESTS if BUILD_GADGETRON=OFF

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF-SuperBuild#228]
On OSX, there are problems with boost 1.69 (brew's current version) and Gadgetron. By setting `BUILD_GADGETRON=OFF`, the rest of SIRF compiles. 

However, this line: `ctest --output-on-failure; test_fail=$?` will always try to run `MR_TESTS_PYTHON`. Is there anything I can do about this?

I think my options are:
1. Put flag e.g., `BUILD_MR_TESTS` in SIRF and propogate to Superbuild
2. In Travis, cd to each of the subfolders (STIR, SIRF, etc.) and run the individual ctests from there

First option seems easier, but I'm wondering if there's an alternative?
@casperdcl @paskino @KrisThielemans

**Comment by casperdcl** [comment]
https://cmake.org/cmake/help/latest/variable/CTEST_CUSTOM_TESTS_IGNORE.html

**Comment by KrisThielemans** [comment]
The SIRF change would be addressed with https://github.com/CCPPETMR/SIRF/pull/353.

**Comment by casperdcl** [comment]
something like if OSX/boost version equals 1.69, append MR_TESTS_PYTHON to CTEST_CUSTOM_TESTS_IGNORE.

**Comment by casperdcl** [comment]
want me to open a PR?

**Comment by rijobro** [comment]
> want me to open a PR?
Would be great if you could. But careful, the `MR_TESTS_PYTHON` would have to get passed down two levels - from the superbuild ctest (all of SIRF) to the individual SIRF ctests. If you can figure how to do that, go ahead!

**Comment by rijobro** [comment]
> The SIRF change would be addressed with CCPPETMR/SIRF#353.

With `DISABLE_Gadgetron`? I don't necessarily want to disable the ISMRMRD wrapping, just the testing (since this requires an instance of Gadgetron to be running).

**Comment by KrisThielemans** [comment]
ah well. It seems a bit strange to me to put in code changes just to accomodate CI, but I agree I see the value of still testing if the ISMRMRD side of things compiles (or even works). We could presumably have yet another (advanced) CMake variable `DISABLE_Gadgetron_tests` (or whatever variation on that name).

@evgueni-ovtchinnikov are there CTests for `sirf.Gadgetron` that don't need `Gadgetron` running?

**Comment by casperdcl** [comment]
ah wait, so really this comes down to skipping `MR_TEST*` iff `gadgetron` doesn't exist (regardless of whether we're building it or not)?

```bash
which gadgetron || export CTEST_ARGS='-E MR_TEST -LE MR_TEST'
...
ctest ${CTEST_ARGS} ...
```

**Comment by rijobro** [comment]
> regardless of whether we're building it or not

This is sort of tricky, since the compilation of our MR code only requires ISMRMRD. However, running it requires Gadgetron. This is why, even though Gadgetron won't be present on Travis, we still want to compile the MR code (just not test it).

Sorry if I've misunderstood, but in your quoted code it looks like you're telling the superbuild not to test `MR_TEST*`. However, these flags need to get passed from the Superbuild `ctest` to the SIRF `ctest`. Is that what your code snippet does?

**Comment by KrisThielemans** [comment]
could do this for GitHub Actions, but closing until we need that
