### ISSUE TITLE
docker: add gpu-enabled image

### ISSUE THREAD

**Issue by casperdcl** [SyneRBI/SIRF-SuperBuild#255]
may be required for hackathon and future plans

- [ ] ensure compatibility with `nvidia-docker`
- [ ] perhaps use `jupyterhub` instead of single-instance server

**Comment by casperdcl** [comment]
At the top of all the docker-compose files, we need `version: '2.3'` in order for `runtime: nvidia` to work. Can't remember if simply changing that causes any issues. After that we may have to document these steps:

- ensure host is linux
- install nvidia drivers (don't need cuda sdk)
- install nvidia-docker (https://github.com/NVIDIA/nvidia-docker)
- uncomment the `driver: nvidia` line in `docker-compose.yml`

**Comment by KrisThielemans** [comment]
@casperdcl I guess this can be closed as we do have one already?

**Comment by casperdcl** [comment]
https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/docker/docker-compose.srv-gpu.yml pretty much solves this, yes
