### ISSUE TITLE
NIFTYREG depends on Zlib

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#258]
Currently Niftyreg depends on Zlib and it's actually [able](https://github.com/KCL-BMEIS/niftyreg/blob/master/CMakeLists.txt#L91) to build it itself if not found, but we don't pass the appropriate variable. 

Shall we pass `-DBUILD_ALL_DEP` to `NIFTYREG`?

**Comment by rijobro** [comment]
Surely we don't want to build anything that might already be on the user's system. Do you run into an error if `zlib` isn't found by NiftyReg?

**Comment by paskino** [comment]
I built on Scientific Linux 7 which didn't have the system zlib-devel package installed, and it failed.
NIFTYREG will only build if the library isn't found.

**Comment by rijobro** [comment]
Ok, sounds reasonable to me.

**Comment by paskino** [comment]
BTW, I encountered a weird (weird?) version conflict on libpng which was solved by passing `-DBUILD_ALL_DEP=ON` to `NIFTYREG`

**Comment by paskino** [comment]
currently [enabled ](https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/SuperBuild/External_NIFTYREG.cmake#L74)in SuperBuild
