### ISSUE TITLE
travis continues if compilation failed

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#267]
this is at least true on OSX. see #264 for an example where Gadgetron build failed but travis only failed at https://github.com/CCPPETMR/SIRF-SuperBuild/blob/b94c622f631d9b476f92cee05bcea6ec40bc79b3/.travis.yml#L273

**Comment by casperdcl** [comment]
duplicate of #192?

**Comment by KrisThielemans** [comment]
we won't update Travis things anymore
