### ISSUE TITLE
Create ENABLE_OpenMP option in SuperBuild.cmake

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#269]
following [this](https://github.com/CCPPETMR/SIRF-SuperBuild/pull/154/files#r331764891) comment, there should be a SuperBuild-wide option to use or not OpenMP.

**Comment by KrisThielemans** [comment]
do we still want to fix this for 2.1 (final)?

**Comment by KrisThielemans** [comment]
addressed by #303

**Comment by KrisThielemans** [comment]
outdated
