### ISSUE TITLE
CMAKE_BUILD_TYPE is not passed through from SuperBuild to 'External'

### ISSUE THREAD

**Issue by ALEXJAZZ008008** [SyneRBI/SIRF-SuperBuild#301]
The only 'External' that CMAKE_BUILD_TYPE is passed through to (it appears) is ITK.

**Comment by KrisThielemans** [comment]
Need to `mark_as_superbuild`and remove the `EXTERNAL_PROJECT_BUILD_TYPE`

**Comment by KrisThielemans** [comment]
let's look at this after #371
