### ISSUE TITLE
Travis build own boost currently failing

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF-SuperBuild#311]
As per https://api.travis-ci.org/v3/job/626119225/log.txt, Travis was failing with:
```
[ 49%] No install step for 'Boost'
[ 50%] Completed 'Boost'
[ 50%] Built target Boost
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```
I'm not sure what the problem is, but I have disabled from Travis. Can be re-added when the problem is resolved.

**Comment by KrisThielemans** [comment]
Closed as outdated
