### ISSUE TITLE
disable docker builds for PRs or even branches

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#332]
there seems little value in running the docker builds for most PRs. @rijobro says that they are still failing for PRs from forks anyway.

What about enabling docker builds only for commits to `master`? Seems easy enough: https://docs.travis-ci.com/user/conditional-builds-stages-jobs

**Comment by KrisThielemans** [comment]
@casperdcl any objections?

**Comment by casperdcl** [comment]
Is this a duplicate of #331? Just want to make sure it's the same issue first...

**Comment by rijobro** [comment]
> Is this a duplicate of #331? Just want to make sure it's the same issue first...

yes

**Comment by KrisThielemans** [comment]
Relevant here is https://github.com/CCPPETMR/SIRF-SuperBuild/pull/361#issuecomment-601102294

**Comment by casperdcl** [comment]
Ping myself
