### ISSUE TITLE
Code duplication in External_astra-toolbox.cmake

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF-SuperBuild#370]
There's a big `IF`/`ELSE` statement in [External_astra-toolbox.cmake](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/bd77f4eb40ce6842be727977d388860775c2d0d5/SuperBuild/External_astra-toolbox.cmake#L89), that depends on CUDA being present or not. I haven't looked much at it, but I'm positive this could be simplified into modifying strings dependent on the presence of CUDA, and removing ~40 lines of code. 

E.g., when CUDA is present, this is added to the `BUILD_COMMAND`: `--with-cuda=${CUDA_TOOLKIT_ROOT_DIR}`. Instead use `SET(ASTRA_CUDA_OPTIONS "--with-cuda=${CUDA_TOOLKIT_ROOT_DIR}")` such that `ASTRA_CUDA_OPTIONS` is a blank string if CUDA is not present.

**Comment by paskino** [comment]
You are right.
