### ISSUE TITLE
Change docs to SynerBY, from CCPETMR

### ISSUE THREAD

**Issue by AnderBiguri** [SynerBI/SIRF-SuperBuild#373]
There is an explicit git command in 

https://github.com/SynerBI/SIRF-SuperBuild/blob/master/README.md#Clone-the-SIRF-SuperBuild-project

plus the environment variable file `env_ccppetmr.sh` and 4 mentions of it in `README.md`

**Comment by KrisThielemans** [comment]
Probably already addressed in #372. If not, please mention it there.
