### ISSUE TITLE
STIR fails with JSON

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF-SuperBuild#374]
Current compilation with Superbuild gives the following error:
```
[ 34%] Linking CXX executable find_maxima_in_image
/home/rich/Documents/Code/SIRF-SuperBuild/Build/sources/STIR/src/utilities/ctac_to_mu_values.cxx:41:10: fatal error: nlohmann/json.hpp: No such file or directory
 #include <nlohmann/json.hpp>
          ^~~~~~~~~~~~~~~~~~~
```
Looking at External_STIR.cmake, the only mention of JSON is here:
```
list(APPEND ${proj}_DEPENDENCIES "JSON")
```
Which means that none of the paths are getting passed from the SuperBuild level through to STIR, presumably the reason that STIR then can't find the include. 

At any rate, as there are relatively few people that would need the feature in STIR, I would personally quite like to see something along the lines of `STIR_USE_JSON` which defaults to `OFF`. This would then have to get passed to the STIR variable `DISABLE_NLOHMANN_JSON` accordingly. If JSON is desired, then JSON is added as a dependency to STIR (`list(APPEND ${proj}_DEPENDENCIES "JSON")`), and the location of the includes (and libraries if there are any) should also be passed to STIR.

**Comment by KrisThielemans** [comment]
Seems to be an underlying STIR problem as well. Presumably STIR does a `find_package` to see if it can use this library?

Is their a Travis build that shows this problem or do you have it only locally?

**Comment by rijobro** [comment]
I only have it locally. Just checked travis and master is happy. I'm building on linux, so I would have thought that the `DEVEL_BUILD=ON` would be in the same boat (since they should be building with STIR master), but they appear green.

**Comment by KrisThielemans** [comment]
@rijobro. closing this?
