### ISSUE TITLE
docker builds fail

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#379]
https://travis-ci.org/github/SyneRBI/SIRF-SuperBuild/jobs/679337688#L280
```
$ $DCC pull core
Pulling core ... 
ERROR: for core  pull access denied for synerbi/sirf, repository does not exist or may require 'docker login'
pull access denied for synerbi/sirf, repository does not exist or may require 'docker login'
The command "$DCC pull core" failed and exited with 1 during .
```
@casperdcl did I merge the transition PR too early? Sorry

**Comment by casperdcl** [comment]
fixed now; mirrored some missing images from ccppetmr -> synerbi.

**Comment by KrisThielemans** [comment]
I see the 2nd set of docker builds failing at https://travis-ci.org/github/SyneRBI/SIRF-SuperBuild/builds/679337674 but I've restarted the build now, as I'm not sure if this was before or after your fix

**Comment by casperdcl** [comment]
ah different issue - looks like `$PYTHON` is now defined somewhere which is confusing the docker build into using venv rather than conda?
