### ISSUE TITLE
Current v2.1.0 build fails due to ITK

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#380]
The ITK repository in [`version_config.cmake`](https://github.com/SyneRBI/SIRF-SuperBuild/blob/v2.1.0/version_config.cmake#L118) is not anymore valid and the build of 2.1.0 fails.

We should release a v2.1.1 to [fix ](https://github.com/SyneRBI/SIRF-SuperBuild/blob/ca283b90592170dba47ace16f883577e30db254a/version_config.cmake#L117)this.

**Comment by KrisThielemans** [comment]
why do you say this? It works for me. Their homepage still points to this repo

**Comment by paskino** [comment]
I say it because it failed more times for me and I was forced to change the repo to make it work.

**Comment by KrisThielemans** [comment]
weird that you had problems. Close this?

For the record, what did you change it to?
