### ISSUE TITLE
STIR project dependencies have to be set after options

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#382]
we're setting the dependencies based on values of options
https://github.com/SyneRBI/SIRF-SuperBuild/blob/e10fe7bd8c8f28bef06d8eff386dc7b94570bf93/SuperBuild/External_STIR.cmake#L27-L29
which are however only defined later on. That means that
- there will be 2 CMake variables (the cached and non-cached) with conflicting values
- the dependencies are incorrect

**Comment by KrisThielemans** [comment]
@rijobro would you be able to have a look at this in absence of @paskino ? Might also occur in other projects.

**Comment by rijobro** [comment]
mv lines 25-39 in `External_STIR.cmake` after last `option`.
