### ISSUE TITLE
Travis OSX can't find Python

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#390]
#387 OSX job fail 
https://travis-ci.org/github/SyneRBI/SIRF-SuperBuild/jobs/682882291#L5721
```
ls: /usr/local/Cellar/python/.*/Frameworks/Python.framework/Versions/.*: No such file or directory
```

**Comment by rijobro** [comment]
Can you just restart the job? It's got a funny box symbol that I've never seen before (middle one), so might just be a Travis bug.

![image](https://user-images.githubusercontent.com/33289025/81065456-6c091680-8ed3-11ea-9d8c-df483aff2b7d.png)

**Comment by KrisThielemans** [comment]
caused by outdated .travis.yml.
