### ISSUE TITLE
Travis can't find nibabel for DEVEL jobs (linux)

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#391]
Travis fail on #387 
https://travis-ci.org/github/SyneRBI/SIRF-SuperBuild/jobs/682882288#L26522
```
  File "/home/travis/build/SyneRBI/SIRF-SuperBuild/sources/SIRF/src/Registration/pReg/tests/test_pReg.py", line 24, in <module>
    import nibabel as nib
ModuleNotFoundError: No module named 'nibabel'
```

**Comment by rijobro** [comment]
Confusing, the `.travis.yml` contains: `- $PY_EXE -m pip install --user -U numpy deprecation nibabel`

**Comment by KrisThielemans** [comment]
https://travis-ci.org/github/SyneRBI/SIRF-SuperBuild/jobs/682882288#L1594 says
```
$PY_EXE -m pip install --user -U numpy
```
but https://github.com/SyneRBI/SIRF-SuperBuild/blob/debb44ab2b2d0dad447e7e8c7774abb83e420577/.travis.yml#L445

I don't understand

**Comment by rijobro** [comment]
It's ok the travis on the PR was outdated.

**Comment by KrisThielemans** [comment]
Trying to see what Travis is checking out I did
https://travis-ci.org/github/SyneRBI/SIRF-SuperBuild/jobs/682882288#L1429
```
git clone --depth=50 --branch=use-gadgetron-317 https://github.com/SyneRBI/SIRF-SuperBuild.git SyneRBI/SIRF-SuperBuild
cd SyneRBI/SIRF-SuperBuild
git checkout -qf c7536a0231cb025451de22489448b920c4ba060c
```
However, that last step fails for me with
```
fatal: reference is not a tree: c7536a0231cb025451de22489448b920c4ba060c
```
(`-qf` is quiet, force, so nothing relevant)

The travis log doesn't contain this error.

I have no idea what's going on!

**Comment by KrisThielemans** [comment]
> It's ok the travis on the PR was outdated.

ah, but why do I not see this? Am I looking in the wrong place?

**Comment by KrisThielemans** [comment]
outdated .travis.yml in the PR
