### ISSUE TITLE
final 4 docker tests run with old CCPi git-tags

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#398]
See https://github.com/SyneRBI/SIRF-SuperBuild/pull/397#issuecomment-627152430

**Comment by casperdcl** [comment]
One potential solution would be to disable `devel`/master builds on PRs...

**Comment by KrisThielemans** [comment]
sounds good to me. No point in having failures that we know will happen. Unfortunately I don't know how to do this.

**Comment by casperdcl** [comment]
ergo

> Kris Thielemans assigned casperdcl 2 hours ago

will do :)
