### ISSUE TITLE
SIRF-SuperBuild fails with gcc-9

### ISSUE THREAD

**Issue by ALEXJAZZ008008** [SyneRBI/SIRF-SuperBuild#413]
I tried to update to 20.04 however quite a few dependencies will not build or are not available on 20.04 (including a lot of Python2). For instance ACE will not build at all (https://stackoverflow.com/questions/61661076/ace-library-in-ubuntu-20-04) and NiftyRegResp won't build with OpenMP etc.
I can't give an update as I'm just going to downgrade to 18.04 again...

**Comment by rijobro** [comment]
Seems like the answer was just to use a more recent version of ACE - https://stackoverflow.com/a/61663297. Did you do `USE_SYSTEM_ACE` `ON` or `OFF`? I suspect `ON` would have worked, and maybe we need to update our default version for `OFF`. 

Any other dependencies that didn't work?

**Comment by ALEXJAZZ008008** [comment]
I did what you suggested before submitting the issue, that was just one of
the problems I had, I didn't document the others before I reinstalled 18.04.

The script that the superbuild uses to build ACE would still be broken
however.

**Comment by ALEXJAZZ008008** [comment]
For information, I also had trouble with boost, HDF5, NiftyReg and OpenMP,
I expect there would be other issues too. I tried either building these all
separately, installing the package or turning them off (When building
without NiftyReg it still errored out searching for it).

**Comment by rijobro** [comment]
Hm, ok thanks for the report. I suppose we'll cross this bridge soon enough.

**Comment by KrisThielemans** [comment]
NiftyReg does not build with gcc-9: https://github.com/KCL-BMEIS/niftyreg/issues/74 (PR by @casperdcl https://github.com/KCL-BMEIS/niftyreg/pull/75 but not sure when it will be merged).

I'm currently trying with gcc-8  in #855

**Comment by KrisThielemans** [comment]
Travis jobs in #855 indicate that there is no problem when using gcc-8. I've therefore changed the title if this issue.

**Comment by KrisThielemans** [comment]
(Originally posted athttps://github.com/SyneRBI/SIRF-SuperBuild/pull/438#issuecomment-767645811 by @paskino)

CUDA SDK restrict which GCC works: for instance 10.1 won't build with GCC 9
```
[  4%] Building NVCC (Device) object nipet/CMakeFiles/mmr_auxe.dir/src/mmr_auxe_generated_scanner_0.cu.o
In file included from /usr/local/cuda/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/local/cuda/include/crt/host_config.h:129:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
```

**Comment by KrisThielemans** [comment]
> CUDA SDK restrict which GCC works: for instance 10.1 won't build with GCC 9

Best to create an issue for NiftiPET, unless it just means that your CUDA SDK is out-of-date

**Comment by KrisThielemans** [comment]
I've created https://github.com/SyneRBI/SIRF/wiki/Known-problems-with-system-configurations#gcc-9-or-later

**Comment by casperdcl** [comment]
> > CUDA SDK restrict which GCC works: for instance 10.1 won't build with GCC 9
> 
> Best to create an issue for NiftiPET, unless it just means that your CUDA SDK is out-of-date

You need CUDA 11 if you need GCC 9.

**Comment by paskino** [comment]
I think that the GCC9 + CUDA SDK is just a version issue. Of course this will create the problem that GPU's whose driver doesn't support the appropriate runtime for SDK11 will not work.

It's nice to know, anyhow.

**Comment by casperdcl** [comment]
> driver doesn't support the appropriate runtime for SDK11 will not work.

indeed - `450` or later required for CUDA 11.

**Comment by casperdcl** [comment]
https://github.com/KCL-BMEIS/niftyreg/pull/75 finally merged :sweat_smile: FYI

**Comment by KrisThielemans** [comment]
#638 finally got us updated

**Comment by KrisThielemans** [comment]
All resolved now. This works fine on my VM.

**Comment by KrisThielemans** [comment]
reopening as ACE doesn't build
```
In file included from /home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ACE/build/source/ace/OS_NS_stropts.h:30,
                 from /home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ACE/build/source/ace/OS_NS_sys_socket.h:28,
                 from /home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ACE/build/source/ace/ACE.inl:5,
                 from /home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ACE/build/source/ace/ACE.h:887,
                 from /home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ACE/build/source/ace/ACE.cpp:1:
/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ACE/build/source/ace/os_include/os_stropts.h:56:17: fatal error: stropts.h: No such file or directory
```
https://github.com/SyneRBI/SIRF-SuperBuild/runs/4894731269?check_suite_focus=true#step:7:3604

our ACE version is out-of-date: https://stackoverflow.com/questions/61661076/ace-library-in-ubuntu-20-04
