### ISSUE TITLE
env_ccppetmr.csh/.sh -> env_ccpsynerbi.csh/.sh

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF-SuperBuild#418]
We still have `env_ccppetmr.csh.in/.sh.in` and still install `env_ccppetmr.csh/.sh`. Should be `env_ccpsynerbi.csh/.sh`.

**Comment by KrisThielemans** [comment]
indeed. we discussed this somewhere, but I cannot find it.

The suggestion was to rename as you suggest, but to either copy or [symlink](https://cmake.org/cmake/help/v3.15/command/file.html#create-link) to the old name at least for the next version.
