### ISSUE TITLE
CMake Error: Could NOT find Python2 (missing: Python2_LIBRARY Python2_INCLUDE_DIR    Development)

### ISSUE THREAD

**Issue by mscipio** [SyneRBI/SIRF-SuperBuild#446]
![image](https://user-images.githubusercontent.com/17526160/101956212-2d57df00-3bcd-11eb-9c2b-cea634fbe64f.png)

Hello,
I was trying to build the SuperBuild from scratch, as my cluster doesn't allow me to use docker for some security reason, but I get this error at the very beginning of the compilation process.
I am using a freshly created conda environment with python 3.8 and cmake 3.12.2.

Why is it looking for a version of python 2?

EDIT: this might be related to #48

**Comment by KrisThielemans** [comment]
It seems your CMake is rather old. Recent versions should first look for python3. It's conceivable that your python is too recent such that it doesn't find it by default. See the [FindPythonInterp doc](https://cmake.org/cmake/help/latest/module/FindPythonInterp.html).

 I guess that if you'd install CMake via conda, you might be alright (you would have to start from scratch though).

Alternatively, you could set `PYVER=3`, or (more reliably) set `PYTHON_EXECUTABLE=/wherever/python3`, e.g.
```sh
cmake -DPYTHON_EXECUTABLE=`which python3` ....
```
or set `Python_ADDITIONAL_VERSIONS`

**Comment by paskino** [comment]
@mscipio this problem may also made worse by NiftyPET which requires Python2?

You could disable it by `-DUSE_NiftyPET=OFF` I think or with `-DUSE_NiftyPET:BOOL=OFF`

**Comment by KrisThielemans** [comment]
Closing as no feedback and more than likely obsolete.
