### ISSUE TITLE
create .zenodo.json

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#465]
I've enabled zenodo upload, as the SuperBuild contains files to run Docker (and in the future Vagrant), so best to have zenodo know where to put it.

**Comment by casperdcl** [comment]
indeed... [![](https://zenodo.org/badge/DOI/10.5281/zenodo.4408776.svg)](https://doi.org/10.5281/zenodo.4408776)
