### ISSUE TITLE
update CIL support

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#475]
we currently have 2 unmerged branches for CIL. This needs to be merged somehow.
https://github.com/SyneRBI/SIRF-SuperBuild/tree/update_cil_2011 and https://github.com/SyneRBI/SIRF-SuperBuild/tree/update_cil_master

@paskino could you take care of this (don't forget to add a line to `CHANGES.md`)

**Comment by paskino** [comment]
CIL has introduced a backward incompatibility from 20.09 to [20.11](https://github.com/vais-ral/CCPi-Framework/blob/master/CHANGELOG.md) as the python module has been renamed!

The 2 branches refer to the 2 different versions of CIL. I'd like to tag this repo for building CIL 20.09. This was the branch `update_cil_master` which I renamed to [`update_cil_2009`](https://github.com/SyneRBI/SIRF-SuperBuild/tree/update_cil_2009)

The other branch refers to the newest version of CIL and different structure of the package.

**Comment by paskino** [comment]
closed by #478 and
closed by #481
