### ISSUE TITLE
Drop Python 2.7 support

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#484]
Python 2.7 has reached in 2020 end of life. 

We need to drop support for Python 2.7.

**Comment by KrisThielemans** [comment]
Some items (please add anything that's missing)
- [ ] change SIRF CMakeLists.txt to require Python v3
- [ ] change SIRF-Superbuild CMakeLists.txt to require Python v3
- [ ] update NiftyPET, needs STIR mod https://github.com/UCL/STIR/issues/795
- [ ] drop from Travis https://github.com/SyneRBI/SIRF-SuperBuild/issues/485 (already done for SIRF)
- [ ] change VM
- [ ] change Dockerfile
- [ ] change `LongTermPlan.md`
- [ ] change documentation
- [ ] change wiki
- [ ] announce on lists

**Comment by KrisThielemans** [comment]
can leave NiftyPET for later, but need to do the rest

**Comment by KrisThielemans** [comment]
I've updated the task list above as some of it was obsolete by now, so it just needs a look at the doc.

**Comment by paskino** [comment]
I added a [line ](https://github.com/SyneRBI/SIRF/wiki/SIRF-and-Python)saying that we refer to Python3 as the only supported Python from SIRF 3.0.

**Comment by KrisThielemans** [comment]
closing as we have a separate issue for NiftyPET #494
