### ISSUE TITLE
Bump SIRF version in master

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#489]
As discussed in https://github.com/SyneRBI/SIRF/issues/858 there is a bug in SIRF 2.2.0 which is built by default [here](https://github.com/SyneRBI/SIRF-SuperBuild/blob/08ffeb5ca408a753b923d24a0489d5844d47a313/version_config.cmake#L199) and leads to travis failures.

**Comment by KrisThielemans** [comment]
fixed in #498 (and earlier)
