### ISSUE TITLE
Why are OpenMP flags and directories passed to external projects?

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#502]
I am using the intel compiler and I cannot build for instance parallelproj with OpenMP because we are passing somehow the flags and libraries found to external project via [these lines](https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/SuperBuild.cmake#L230L236)

```cmake

mark_as_superbuild(ALL_PROJECTS VARS 
      OpenMP_CXX_FLAGS:STRING OpenMP_CXX_LIB_NAMES:STRING OpenMP_C_FLAGS:STRING 
      OpenMP_C_LIB_NAMES:STRING OpenMP_CXX_FLAGS:STRING OpenMP_CXX_LIB_NAMES:STRING 
      OpenMP_libomp_LIBRARY:FILEPATH OpenMP_omp_LIBRARY:FILEPATH
      OpenMP_gomp_LIBRARY:FILEPATH OpenMP_pthread_LIBRARY:FILEPATH
      OPENMP_INCLUDES:PATH OPENMP_LIBRARIES:PATH
      )
```

This seems to prevent the project's own `find_package(OpenMP)` to set the variable it requires, probably because `find_package` looks in the cache before executing. I get the a message that says that the `OpenMP_iomp_LIBRARY` variable isn't set and the build of the external project fails at cmake configure time. 

The solution is to add `OpenMP_iomp_LIBRARY` to the variables in `mark_as_superbuild`. However, `OpenMP_iomp_LIBRARY` is a variable that has meaning only if one tries to build with the intel compiler, while the others seem to be applying to GCC. So, while adding the variable solves the issue, I don't think we should maintain such a list at all.

Actually, removing the above code in ~~`mark_as_advanced`~~ `mark_as_superbuild` makes it work as well.

So the question is why do we pass such variables at all?

**Comment by KrisThielemans** [comment]
@rijobro had to add the capability to pass explicit OpenMP flags, as `find_package(OpenMP)` didn't work on his OSX,`brew`,`AppleClang` or whatever combo. Hence, we have lines like https://github.com/SyneRBI/SIRF-SuperBuild/blob/9fec2b91b67a6d21fbf60d9b06e07d5d75e7858f/SuperBuild/External_parallelproj.cmake#L45-L46
Passing these variables isn't necessary on Linux nor Windows as far as I know. However, disabling that functionality seems like a bad idea.

This seems independent however to adding variables to `mark_as_superbuild`. This is a macro that then automatically adds the related variables to the `CMAKE_ARGS` of all dependent projects. We originally used this strategy to make our life easier (i.e. avoid doing it by hand). Not sure if that was a good idea...

> Actually, removing the above code in `mark_as_advanced` makes it work as well.

I'm guessing that was a typo, and you meant `mark_as_superbuild`.

I'm all in favour of removing the above `mark_as_superbuild`  statement. It introduces specific variables, which apparently create trouble. It is possible that we'll need to add `OpenMP_CXX_FLAGS` in the dependenct projects, but I hope not. As we currently don't run MacOS tests at all, we will only find out when somebody tells us.

So, I suggest to do the following:
- remove the `mark_as_superbuild` lines you quote
- create a variable `OpenMP_CMAKE_ARGS` setting `OPENMP_INCLUDES` and `OPENMP_LIBRARIES`
- use that variable in all dependent projects where we currently have OpenMP flags, just like we do with Python.

**Comment by paskino** [comment]
see also #95

**Comment by KrisThielemans** [comment]
> I'm all in favour of removing the above mark_as_superbuild statement. It introduces specific variables, which apparently create trouble. 

Actually, I take this comment back. `mark_as_superbuild` is equivalent to us creating a variable and passing that, but it's easier, as we don't have to know which dependencies need OpenMP.

So, it's better to pass the `iomp` library
