### ISSUE TITLE
changing version_config.cmake doesn't change git tags once already compiled

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#51]
version_config.cmake sets `SIRF_TAG` as cached variables. However, this means that once you build, they never get changed (unless you force it). In particular, doing a `git pull` might change `version_config.cmake` but that still won't change the cahced variables, so you'll be building the same version.

The only way around it is to run cmake again, e.g.
```
cmake -DGadgetron_TAG=00b96376568278a595e78879026bb3b0d5fbb98d  -DGadgetron_URL=https://github.com/gadgetron/gadgetron .
```
This is in particular a problem for the VM, as updating the VM now no longer works as expected.

@casperdcl, any ideas?

**Comment by casperdcl** [comment]
I thought the VM would always have `..._TAG=master` and if people manually change that then it's reasonable to expect them to manually upgrade.

**Comment by KrisThielemans** [comment]
at present, we set it to a specific tag for SIRF. We could use master probably (people might expect that `update_VM.sh` just gets them the most recent development version) but then the same problem still holds for `Gadgetron_TAG` etc. I don't think we can run the risk of picking up the most recent Gadgetron or STIR, but on the other hand, SIRF-master might need a newer version of Gadgeton/STIR. Our plan is to encode this in the SuperBuild `version-config.cmake` but this doesn't seem to be enough.

For the VM, I have a separate https://github.com/CCPPETMR/CCPPETMR_VM/issues/31 with a suggested solution. Let's continue the VM discussion there.

For the SuperBuild itself, I think it's a surprising side-effect of our set-up, but I don't see an easy solution.

**Comment by casperdcl** [comment]
related to #4

**Comment by casperdcl** [comment]
well we could include re-running cmake as part of the update script

**Comment by KrisThielemans** [comment]
no, I don't think this is related to #4 after all. I've checked the dependencies generated by CMake and version-config.cmake et al are listed. 
Indeed, running cmake itself doesn't change anything to the checked-out clones, unless you change cached variables of course.

**Comment by paskino** [comment]
We  could we use the rebuild_cache [target ](https://cmake.org/runningcmake/)

> rebuild_cache – This target runs cmake on the source tree and picks up additional cache entries if they exist.

**Comment by KrisThielemans** [comment]
@paskino can you document the solution we use on the VM, I guess in https://github.com/CCPPETMR/SIRF/wiki/Rebuilding-after-upgrades

**Comment by KrisThielemans** [comment]
@paskino, please add instructions on how to update. (i.e. do what you do on the VM)

**Comment by KrisThielemans** [comment]
documented on the wiki. Try to resolve this later.

**Comment by KrisThielemans** [comment]
There isn't much we can do about this, and we have some doc already on updating, so closing.
