### ISSUE TITLE
docker build on Travis fails

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#522]
We finally got Travis credit again. Sadly, docker builds fails, see https://travis-ci.com/github/SyneRBI/SIRF-SuperBuild/jobs/499291359#L1001-L1004 with
```
if [ -f requirements.txt ]; then
  ${PYTHON} -m pip install -U -r requirements.txt
fi
user_python-ubuntu.sh: line 37: miniconda: command not found
```
Relevant line is [here](https://github.com/SyneRBI/SIRF-SuperBuild/blob/6605a5a1e3a3d219aef9adc0da8202060b5bd6e8/docker/user_python-ubuntu.sh#L37).

I never understood this line. Why would `miniconda -m pip install...` work?

My feeling is that we need something like this after https://github.com/SyneRBI/SIRF-SuperBuild/blob/6605a5a1e3a3d219aef9adc0da8202060b5bd6e8/docker/user_python-ubuntu.sh#L18
```
PYTHON=`which python`
```

But 
- I don't know why we'd be using `miniconda` in the first place as opposed to system `python3` (which we're installing).
- Although `docker` doesn't, we currently use `virtualenv` in our (preliminary) [ctest_sirf.sh](https://github.com/SyneRBI/SIRF-SuperBuild/blob/6605a5a1e3a3d219aef9adc0da8202060b5bd6e8/docker/ctest_sirf.sh#L8), currently only used for GHA.

@casperdcl can you provide a clue?

**Comment by casperdcl** [comment]
https://github.com/SyneRBI/SIRF-SuperBuild/commit/6605a5a1e3a3d219aef9adc0da8202060b5bd6e8 introduced a bug, not sure why @paskino made this change:

https://github.com/SyneRBI/SIRF-SuperBuild/blob/6605a5a1e3a3d219aef9adc0da8202060b5bd6e8/docker/user_python-ubuntu.sh#L37

What was wrong with `pip install -U -r requirements.txt`?

`${PYTHON}` isn't necessarily a path to an executable (it could just be `miniconda`, which is a flag to signify "please install miniconda").

**Comment by KrisThielemans** [comment]
ah. I didn't see this was a change introduced by @paskino. sorry. I should have.

> What was wrong with `pip install -U -r requirements.txt`?

we've switched to `python3`. Will that work for both `miniconda` as well as `python3`? (maybe it does, because of the `virtualenv`. I confess I don't know...)

**Comment by KrisThielemans** [comment]
ok. well, at least the GHA worked for the PR, and it picked up the correct `python3` etc. The PR doesn't do most of the `docker` stuff yet of course. I'll just merge it as it looks fine to me.

Thanks!

**Comment by casperdcl** [comment]
Both miniconda & virtualenv are activated as appropriate in the script so `pip` should just work as expected.

**Comment by KrisThielemans** [comment]
ok great. thanks for the clarification!

Waiting to see what Travis does. We'll need to get rid of the non-docker test jobs in Travis as it's running out of credits too fast. Of course, we should port the travis docker stuff to GHA really, but that seems non-trivial...

**Comment by DANAJK** [comment]
👏

**Comment by KrisThielemans** [comment]
this worked, but...
- it only pushed `devel` (and `core*`) as per [the travis file](https://github.com/SyneRBI/SIRF-SuperBuild/blob/988d3a7df73dc975aff203b8f29b512e85b25200/.travis.yml#L210-L214). This means we do not get a new v2.2 using python3, but I guess that's ok.
- there is no `devel-service` at present. On the other hand, i cannot plot from in there as the `matplotlib` backend is set to `Agg` for some reason.
- `devel` doesn't have `jupyter`. I installed it in my local container with `pip install jupyter`, but struggled to get the port forwarding to work.

Seems I have to learn more...

**Comment by DANAJK** [comment]
Thanks. I would prefer to start from something that is close to what the course participants will have.
