### ISSUE TITLE
docker: run ./sirf-compose-server up -d sirf fails

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#534]
Following the instructions in the [README ](https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/docker/README.md#tldr-i-want-a-jupyter-notebook-service-now) (point 4) I type

```bash 
sirfuser@vagrant:~/devel/SIRF-SuperBuild/docker$ ./sirf-compose-server up -d sirf

[ ...  lots of output ...]

Step 43/60 : COPY devel/.ccache/ /opt/ccache/
ERROR: Service 'sirf' failed to build: COPY failed: file not found in build context or excluded by .dockerignore: stat devel/.ccache/: file does not exist
```

However

```bash 

 sirfuser@vagrant:~/devel/SIRF-SuperBuild/docker$ stat devel/.ccache
  File: devel/.ccache
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fd00h/64768d    Inode: 393745      Links: 2
Access: (0775/drwxrwxr-x)  Uid: ( 1001/sirfuser)   Gid: ( 1001/sirfuser)
Access: 2021-05-11 09:41:27.851757421 +0000
Modify: 2021-05-11 09:41:27.851757421 +0000
Change: 2021-05-11 09:41:27.851757421 +0000
 Birth: -
```

Notice that the `sirfuser `must be in the `docker `group.

**Comment by casperdcl** [comment]
[rtfd](https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/docker/README.md#tldr-i-want-a-jupyter-notebook-service-now) 

> Note that starting the container may take a few minutes the first time, but only a few seconds afterwards. (Run `docker logs -f sirf` to see the container's progress - eventually there should be a message stating the notebook has started.) ...

**Comment by KrisThielemans** [comment]
This is all resolved now

**Comment by KrisThielemans** [comment]
Reopening as I still have a similar error message as @paskino wrote  initially:
```
sirfuser@vagrant:~/devel/SIRF-SuperBuild/docker$ ./sirf-compose-devel-server  build sirf
<snip>
Step 43/61 : COPY devel/.ccache/ /opt/ccache/
ERROR: Service 'sirf' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder998097261/devel/.ccache: no such file or directory
```
So, this was not a permission problem writing to `/devel`

**Comment by KrisThielemans** [comment]
Cause is https://github.com/SyneRBI/SIRF-SuperBuild/blob/32b0126e00dd69b15b3223fb1b8334e2d5804bcf/docker/Dockerfile#L78
which fails if `.../SIRF-SuperBuild/docker/.ccache` does not exist. This isn't a problem on Travis as @casperdcl does some smart stuff there to re-use the Travis ccache, such that the docker build is a lot faster.
https://github.com/SyneRBI/SIRF-SuperBuild/blob/32b0126e00dd69b15b3223fb1b8334e2d5804bcf/.travis.yml#L136-L144.

I guess we could solve this by adding an empty `SIRF-SuperBuild/docker/.ccache` in git. I suppose we could even modify `sirf-compose` to do the trick that is currently done on Travis.

**Comment by KrisThielemans** [comment]
in fact, we have a `devel/.cache` already. However, it is  somehow the `COPY` fails. Presumably this is because of our `.dockerignore`
https://github.com/SyneRBI/SIRF-SuperBuild/blob/32b0126e00dd69b15b3223fb1b8334e2d5804bcf/docker/.dockerignore#L1-L2
Although [the doc](https://docs.docker.com/engine/reference/builder/#dockerignore-file) says
> Lines starting with ! (exclamation mark) can be used to make exceptions to exclusions. 

Using the trick in
https://github.com/SyneRBI/SIRF-SuperBuild/blob/32b0126e00dd69b15b3223fb1b8334e2d5804bcf/.travis.yml#L145
resolves the problem, but surely that cannot be right.

@casperdcl not sure if you have time to help with this one?

**Comment by paskino** [comment]
maybe there is a difference with the ubuntu18.04 base image and the nvidia one wrt to the user/permissions?

**Comment by KrisThielemans** [comment]
> Maybe there is a difference with the ubuntu18.04 base image and the nvidia one wrt to the user/permissions?

can't see why, but I have been wrong many times before!

I suppose you should try and build a normal one.

Maybe there's also a difference in docker version and its treatment of `.dockerignore`.

**Comment by paskino** [comment]
So, both of the `service-gpu` or `service` image have this error. 

I then tried to remove `.dockerignore` and it works, so I suppose the first line needs to go 
https://github.com/SyneRBI/SIRF-SuperBuild/blob/0e4a5eb575bdf80ff4c3fdf8643777f2f941e11d/docker/.dockerignore#L1
and we need to list the content of the directory we want docker to discard?

Or possibly invert the discard/not discard lines?
