### ISSUE TITLE
docker: sirf-compose-devel-server etc are incorrect

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#537]
they get the wrong image.

**Comment by KrisThielemans** [comment]
@paskino this explains why it starts downloading again even if you have pulled it

**Comment by casperdcl** [comment]
You should be doing e.g. `./sirf-compose-devel-server build --pull` - haven't checked but I doubt that pulls the wrong image.

**Comment by KrisThielemans** [comment]
Sorry @casperdcl , I cannot get my head round it.

I successfully pulled the `sirf:devel-service` image (confirmed with `docker images`). However, I cannot succeed in just running it (without pulling again). I thought the following would force it
```
./sirf-compose-devel-server  up -d --no-recreate --no-build sirf
```
but then it just says that `ERROR: service sirf needs to be built, but --no-build was passed`. I've added `--verbose` which gives me too much info that I don't understand (full log below), but at the very end it says
```
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('synerbi/sirf:service')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.30/images/synerbi/sirf:service/json HTTP/1.1" 404 87
compose.cli.main.main: Service 'sirf' needs to be built, but --no-build was passed.
```
So it want the `service` image, which is incorrect.

I think this is because I set-up the chaining in Travis wrong:
https://github.com/SyneRBI/SIRF-SuperBuild/blob/f9cdbc45fbeac3b5a9ccc25c51e0382564176b28/.travis.yml#L120-L121
i.e. `service-devel` will be built with `docker-compose.srv.yml` which might make it refer to `service`.

My feeling now is that we need a ``docker-compose.srv-devel.yml` , but it'd be a pity as that means proliferating the `yml` files (which you avoided).

Anyway, if you can help, I'll appreciate it 😄 

[docker.log](https://github.com/SyneRBI/SIRF-SuperBuild/files/6474956/docker.log)

**Comment by KrisThielemans** [comment]
This works now. Not sure what fixed it...
