### ISSUE TITLE
docker: docker-compose.yml and 2 Gadgetrons?

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#539]
At present we're building Gadgetron as part of the docker image (as it's the default). In addition, we use the latest Gadgetron docker image
https://github.com/SyneRBI/SIRF-SuperBuild/blob/f9cdbc45fbeac3b5a9ccc25c51e0382564176b28/docker/docker-compose.yml#L35-L37
It seems to me therefore that we have Gadgetron twice at the moment.

One sign of this was that if I pull `sirf:latest` and then `sirf-compose up`, docker will pull the Gadgetron image.

I've tried to comment out the Gadgetron lines in `docker-compose.yml` and indeed the image starts fine and I can start gadgetron and run some MR demos.

My feeling is therefore that we should for now comment those lines out, and look into using the Gadgetron docker image later.

@casperdcl what do you think?

**Comment by casperdcl** [comment]
You're not running those lines since `./sirf-compose-*` does `docker compose ... sirf` and not `docker-compose ...` nor `docker-compose ... gadgetron`.

**Comment by KrisThielemans** [comment]
Clearly I don't understand all of this well enough. sorry.

At present it doesn't seem to: https://github.com/SyneRBI/SIRF-SuperBuild/blob/f9cdbc45fbeac3b5a9ccc25c51e0382564176b28/docker/sirf-compose#L3

Indeed, if I do `./sirf-compose-devel up --no-start sirf`, it doesn't download the Gadgetron image. However, without the extra `sirf` argument it does. In fact, this probably explains while I seem to have a `sirf:core` image running as well (which I don't think should be the case).

So, are we missing a `sirf` argument? (Possibly one of my edits!). If so, where should it be (after the `$@` or before?)

**Comment by casperdcl** [comment]
Yes if you notice all the `$DCC` commands from https://github.com/SyneRBI/SIRF-SuperBuild/blob/f9cdbc45fbeac3b5a9ccc25c51e0382564176b28/.travis.yml#L124 specify a target (e.g. `$DCC build sirf`).

The README (https://github.com/SyneRBI/SIRF-SuperBuild/tree/master/docker#tldr-i-want-a-jupyter-notebook-service-now) wuite clearly states `sirf` everywhere too.

Not sure about side-effects of trying to make things more convenient by commenting out things. Don't have time to investigate but feel free to change & debug things yourself!

**Comment by KrisThielemans** [comment]
Yes indeed. One of those questions where I should have read the manual.

I agree with you that it is best to leave this until we have time (?) to investigate a different set-up. The current one works great anyone. Thanks.
