### ISSUE TITLE
docker: requirements

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#543]
If I understand correctly, the docker image uses miniconda python.

`Dockerfile` calls [`user_python-ubuntu.sh`](https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/docker/Dockerfile#L73) without parameters, which means that it's going to install to `/opt/pyenv` and use `miniconda` as default python.

It later uses `requirements.txt` to install via `pip`. 

Probably, for the training we will need to add some additional [dependencies ](https://github.com/TomographicImaging/CIL/blob/master/recipe/meta.yaml#L64L66)for CIL, either via pip or conda.

**Comment by KrisThielemans** [comment]
In many cases, `requirements.txt` seems to be usable for both `conda` and `pip`, but not always (i.e. the `--only-binary` option doesn't work on `conda` , although I don't know why we use it for `pip` `matplotlib`).

I have no understanding of why it (dis)advantages of using `pip` in a `conda` install. I guess `pip` has more than `conda`, but I guess if `conda` packages are available it'd make sense to use them. Or maybe it's all the same...

See also discussion in  #493 on how to avoid having to track the requirements separately (but would require `CIL-demos` to have a `requirements.txt` presumably

**Comment by KrisThielemans** [comment]
done?
