### ISSUE TITLE
Docker: problems with server GPU

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#547]
I've run 
```

docker pull synerbi/sirf:service-gpu

./sirf-compose-server-gpu up -d sirf

Creating network "docker_default" with the default driver
Creating sirf ... error

ERROR: for sirf  Cannot create container for service sirf: Unknown runtime specified nvidia

ERROR: for sirf  Cannot create container for service sirf: Unknown runtime specified nvidia
ERROR: Encountered errors while bringing up the project.
```

My machine has 
```
[edo@vishighmem01 docker]$ nvidia-smi
Wed Jun  2 14:54:44 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.52.18    Driver Version: 418.52.18    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   50C    P8    15W / 280W |    284MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     18694      C   ...s/miniconda3/envs/cil2_demos/bin/python   137MiB |
|    0     19798      C   ...s/miniconda3/envs/cil2_demos/bin/python   137MiB |
+-----------------------------------------------------------------------------+
```

**Comment by paskino** [comment]
The solution is achieved by following these steps:


  - https://github.com/NVIDIA/nvidia-docker/wiki/Frequently-Asked-Questions#why-do-i-get-the-error-unknown-runtime-specified-nvidia
  - https://github.com/nvidia/nvidia-container-runtime#installation
  - https://nvidia.github.io/nvidia-container-runtime/

**Comment by KrisThielemans** [comment]
@paskino found that the docker image hasn't been built with GPU support. Confirmed at
https://travis-ci.com/github/SyneRBI/SIRF-SuperBuild/jobs/506993066#L4458

Possibly a travis or CMake issue as this seems fine
https://github.com/SyneRBI/SIRF-SuperBuild/blob/52510c972001a450cec397259504b5b26d44c37c/docker/docker-compose.srv-gpu.yml#L17

@paskino , are NVIDIA libraries in the container? Does CMake find them, or maybe it needs a hand.

You could also `docker pull synerbi/sirf:core-gpu` (bare-bones system) to experiment I guess.

**Comment by paskino** [comment]
running `./sirf-compose-server-gpu up -d sirf` after some time I see (see image below) in one of the projects which looks for CUDA that it's not found. 

What I really don't understand is this: 

1. Dockerfile [says ](https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/docker/Dockerfile#L1L2)it's going to build from `BASE_IMAGE=ubuntu:18.04` not from an NVIDIA base image. 
2. However the docker compose file seems to set an environment variable `BASE_IMAGE` to [`nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04`](https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/docker/docker-compose.srv-gpu.yml#L17). Maybe this is the way to start the Docker image from a different base. If this is correct it should start from the NVIDIA image. But it doesn't.


![image](https://user-images.githubusercontent.com/14138589/120519150-38e0d180-c3ca-11eb-906c-25f9a3bd4176.png)

**Comment by paskino** [comment]
I can confirm that the `core-gpu` has nvcc installed.

**Comment by paskino** [comment]
I have changed the first line of the Dockerfile to use the nvidia image and indeed CUDA is found and is being used in the compilation.

I'll let you know.

**Comment by KrisThielemans** [comment]
Looks like #551 fixed the problem that it was using the wrong base image

https://travis-ci.com/github/SyneRBI/SIRF-SuperBuild/jobs/510914821#L346
```
Step 1/61 : ARG BASE_IMAGE=ubuntu:18.04
Step 2/61 : FROM ${BASE_IMAGE} as base
10.0-cudnn7-devel-ubuntu18.04: Pulling from nvidia/cuda
```
https://travis-ci.com/github/SyneRBI/SIRF-SuperBuild/jobs/510914821#L1442-L1443
```
-- Found CUDA: /usr/local/cuda (found version "10.0") 
-- <<<<<<<<<<<<<<<<< CUDA FOUND >>>>>>>>>>>>>>>>>>>>>
```

**Comment by KrisThielemans** [comment]
@paskino, we should add the instructions [above](https://github.com/SyneRBI/SIRF-SuperBuild/issues/547#issuecomment-853062125) to our `README`.

Can you take care of it once it all works?

**Comment by KrisThielemans** [comment]
Installation instructions added to the README in 7d9f922475435957e8b0bf0161bcf004eeaeb36a
