### ISSUE TITLE
docker: slow startup of container the very first time

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#555]
If you get a new image and start it up, the very first time it can take a long time. Our doc says "a few minutes" (used to say "a few seconds"). For me, it easily takes 15 minutes, but this is docker running inside the VM (which isn't really recommended).

I did the following to check what's going on.
```
./sirf-compose-server up -d sirf
docker exec -w / ps aux
```
repeating the latter a few times.

It turns out it is busy in https://github.com/SyneRBI/SIRF-SuperBuild/blob/32b0126e00dd69b15b3223fb1b8334e2d5804bcf/docker/entrypoint.sh#L34-L39
The longest part seems to be when updating `/opt/pyvenv` (which is where we install miniconda (see [here](https://github.com/SyneRBI/SIRF-SuperBuild/blob/6d0db321393e13aa6428dea808e46a30a74f3545/docker/user_python-ubuntu.sh#L40) and [here](https://github.com/SyneRBI/SIRF-SuperBuild/blob/6d0db321393e13aa6428dea808e46a30a74f3545/docker/user_python-ubuntu.sh#L12)), although it takes it time with `/opt/SIRF-Superbuild` (which is the build directory) as well of course.

Any ideas to speed this up?

(It seems non-trivial to avoid this, as docker file permissions need to know who the "host" user is, see #464)

**Comment by KrisThielemans** [comment]
Interesting is that once the container is up, another `chown -R` /opt/ccache` etc is lightning fast. I presume that this is because the first time, the container will need to create its own copy of all the files (starting from what's in the image), while the second time that is already done.

**Comment by KrisThielemans** [comment]
Questions:
- can someone with a Linux machine (@AnderBiguri ?) pull `latest` and start it (see the README) and report back how long it takes?
- Do most of these `/opt` directories actually need to be owned by `sirfuser`? Why not keep them owned by `root` but make them writable by everyone. That way, the `chmod` can be done at image creation time (e.g. on Travis), as opposed to container creation time (by the user). (I've done a small experiment  where `conda install`, `pip install`, and some compilation etc worked all fine)

**Comment by AnderBiguri** [comment]
Will test today!

**Comment by AnderBiguri** [comment]
@KrisThielemans 

In Step 4, after ignoring step 3 of https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/docker/README.md

I get the following:

```
~/DOCKER_test/SIRF-Superbuild/docker$ ./sirf-compose-server-gpu up -d sirf
ERROR: The Compose file './docker-compose.srv-gpu.yml' is invalid because:
Unsupported config option for services.gadgetron: 'runtime'
Unsupported config option for services.sirf: 'runtime'
```

Then I did Step 3 and it worked for the non-gpu one, but not the gpu one (same error). 

When starting it for the first time, it has been at least 3 or 4 minutes on step

`Updating file permissions for /opt/pyvenv`

Now its been 3 minutes or so on step

`Updating file permissions for /opt/SIRF-SuperBuild`

The rest are faster. But yes, in total I'd say 10 minutes or so to start it up, on a pretty good machine (16 cores) and no VM.

**Comment by KrisThielemans** [comment]
Thanks @AnderBiguri, did you do the last bit of step 1 "install the NVidia container runtime"? I suspect that this caused your error.

Main observation therefore is the run time. Unacceptable I think. I'll try something else in #558

**Comment by AnderBiguri** [comment]
@KrisThielemans Yes, I did of course. Will fiddle with that a bit more, as nvidia is nvidia. 

But indeed, it is very long time.

**Comment by KrisThielemans** [comment]
> `Unsupported config option for services.gadgetron: 'runtime'`

Seems to be that you have a too old `docker-compose`, see https://stackoverflow.com/questions/36724948/docker-compose-unsupported-config-option-for-services-service-web, although it could also be too new. Mine is
```
$ docker-compose --version
docker-compose version 1.17.1, build unknown
```
