### ISSUE TITLE
Dockerfile license is Mozilla MPL2.0

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#559]
The license of the [Dockerfile ](https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/docker/Dockerfile#L10)is Mozilla 2.0 and is different for the rest of SIRF.

**Comment by casperdcl** [comment]
This is no longer the case as per https://github.com/SyneRBI/SIRF-SuperBuild/blob/8ca50676b4b3140beb960dc76f2f6ef5d2468ba4/.github/workflows/docker.yml#L51 (fixed by #718)
