### ISSUE TITLE
docker: when to install CIL prerequisites

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#562]
Part of CIL prerequisites are listed in https://github.com/SyneRBI/SIRF-SuperBuild/blob/0e4a5eb575bdf80ff4c3fdf8643777f2f941e11d/docker/requirements.txt#L4-L11 however, 2 are missing: `PyWavelets` and `dxchange` which are not available on pip but are on `conda-forge`.

Given that the docker image is using conda python I suggest to change
https://github.com/SyneRBI/SIRF-SuperBuild/blob/0e4a5eb575bdf80ff4c3fdf8643777f2f941e11d/docker/user_python-ubuntu.sh#L35-L43

as
```bash 


# Python (runtime)

if [ "$PYTHON" = "miniconda" ]; then
  if [ -f requirements.txt ]; then  
    conda install --yes --file requirements.txt  
  fi
  conda update -c conda-forge -y --all
  conda clean -y --all
else
  if [ -f requirements.txt ]; then  
    pip install -U -r requirements.txt
  fi
fi

 

```

**Comment by paskino** [comment]
maybe better

```bash 
if [ -f requirements.txt ]; then  
  if [ "$PYTHON" = "miniconda" ]; then
    conda install --yes --file requirements.txt  
    conda update -c conda-forge -y --all
    conda clean -y --all
  else
    pip install -U -r requirements.txt
  fi
fi
```

**Comment by KrisThielemans** [comment]
ok, but as they're not on `pip` (amazing...), what about creating a `requirements.yml` where they're added, and use
```sh
if [ "$PYTHON" = "miniconda" ]; then
  if [ -f requirements.yml]; then  
    conda install --yes --file requirements.yml
  elif [ -f requirements.txt ]; then  
    conda install --yes --file requirements.txt  
  fi
else # pip
 ...
fi
```
