### ISSUE TITLE
Try ISMRMRD 1.4.2 or even 1.5.0

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF-SuperBuild#567]

**Comment by KrisThielemans** [comment]
This will more than likely need upgrading Gadgetron to 3.17 #305 or later #438

**Comment by KrisThielemans** [comment]
- [ ] #568 
- [ ] https://github.com/SyneRBI/SIRF/issues/948

**Comment by KrisThielemans** [comment]
closed by #621
