### ISSUE TITLE
ISMRMRD 1.4.2 linking errors with HDF5

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#568]
when building on Ubuntu 18.04 (docker) we get
```
libhdf5.so.103, needed by /opt/SIRF-SuperBuild/INSTALL/lib/libismrmrd.so, not found
```
https://travis-ci.com/github/SyneRBI/SIRF-SuperBuild/jobs/512743253#L6251

**Comment by KrisThielemans** [comment]
from the same job https://travis-ci.com/github/SyneRBI/SIRF-SuperBuild/jobs/512732490#L4002
```
HDF5 found at: /opt/pyvenv/include

HDF5 found at: /opt/pyvenv/lib/libhdf5.so;/opt/pyvenv/lib/libcrypto.so;/opt/pyvenv/lib/libcurl.so;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/opt/SIRF-SuperBuild/INSTALL/lib/libz.a;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so
```
which all look fine. ISMRMRD utilities compile fine.

I have the impression it is only dependent projects which fail.

**Comment by KrisThielemans** [comment]
There is no problem on my VM which uses CMAke 3.17. Our docker image uses CMake 3.13 or so.

@paskino, can you check your `install/lib/cmake/ISMRMRD/ISMRMRDTargets.cmake`. Mine says
```
set_target_properties(ISMRMRD::ISMRMRD PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/home/sirfuser/devel/install/lib/libz.a;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so"
)
```

**Comment by KrisThielemans** [comment]
could be a case of upgrading CMake.

**Comment by KrisThielemans** [comment]
> could be a case of upgrading CMake.

I tried with CMake 3.10.2 (i.e. system version in Ubuntu 18.04) and it all works fine.

@paskino is this only in the docker image or are you seeing it elsewhere?

**Comment by paskino** [comment]
it is in the docker image

**Comment by KrisThielemans** [comment]
I've used an existing docker, `git pull` in`/opt/SIRF-SuperBuild` and rebuilt with the updated ISMRMRD. That works. Building a new docker image doesn't work.

weird.

**Comment by KrisThielemans** [comment]
I've built a local docker by editing out the `cmake --build` and `chown` stuff (to save time). If I then go in and do `make siemens_to_ismrmrd` it fails with the above error.

The `ISMRMRDTargets.cmake` looks pretty much like above (but using `/opt/pyvenv/...`) which is correct. Doing a `make VERBOSE=ON` shows that the `libhdf5.so` library is not passed though.

I don't understand...
```

**Comment by paskino** [comment]
In my newly built *almost* working docker image with user `jovyan` I have

```
INTERFACE_LINK_LIBRARIES "/opt/pyvenv/lib/libhdf5.so;/opt/pyvenv/lib/libcrypto.so;/opt/pyvenv/lib/libcurl.so;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/opt/pyvenv/lib/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so"
```

Notice that in this case I forced the SuperBuild at https://github.com/SyneRBI/SIRF-SuperBuild/commit/9767f8adb189474e95f357ba1986e2755ba4a6dd

**Comment by KrisThielemans** [comment]
Underlying problems is described in https://github.com/ismrmrd/siemens_to_ismrmrd/issues/77. The same problem exists in the (very old) Gadgetron that we're still using, but seems fixed in recent Gadgetron.

**Comment by paskino** [comment]
Probably this can be closed thanks to https://github.com/ismrmrd/siemens_to_ismrmrd/pull/79 ?

**Comment by KrisThielemans** [comment]
it would, if we would upgrade `version_config.cmake` to that commit. However, I feel this could do with some testing, as discussed in #621

**Comment by KrisThielemans** [comment]
is being done in #438

**Comment by KrisThielemans** [comment]
we've upgraded to ISMRMRD 1.5.0
