### ISSUE TITLE
docker image for kubernetes jupyterhub

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#569]
We're trying to get an image ready to launch on jupyterhub with kubernetes. Current attempt is on https://github.com/paskino/SIRF-SuperBuild/tree/add_jovyan_user/docker

This does not use `docker-compose`, so our `.yml` files are not used.

Difficulties
- [x] `sirf_env.sh` is not sourced
- [x] the jupyter notebook started in `/home/jovyan`
- [ ] `gadgetron` is not started (but we can tell the user to do that, as they need to do it on the VM anyway)
- [x] user permissions for `/opt` (read-only) - see related discussion in #464, #555 and #558 although they concentrate on using `docker-dompose` -  causing problems (solvable by doing `sudo chown -R jovyan:users /opt/SIRF-Exercises/`)
   - would not be able to modify notebooks
   - cannot download data
      ```
      $ /opt/SIRF-Exercises/scripts/download_data.sh -p ~/data ~/data_download
      ....
      creating data_path.py in /opt/SIRF-Exercises/lib/sirf_exercises/data_path.py
      ./download_data.sh: line 204: /opt/SIRF-Exercises/lib/sirf_exercises/data_path.py: Permission denied
      ```
 - [x] <strike>currently starting JupyterLab, where'd prefer to use the classic interface (can be done by adding `tree` at the URL)</strike> (This is a jupyterlab (system-wide!) setting, not under our control
 - [x] <strike>cannot plot anything</strike> (This disappears when launching classic jupyter)
  ```
  plt.figure()
  plt.plot(1,2)
  Javascript Error: IPython is not defined
  [<matplotlib.lines.Line2D at 0x7f46d0e47580>]
  ```

**Comment by paskino** [comment]
I built the image with docker-compose. The problem is how the image is run, which we don't know. I believe that with a lengthy docker terminal command one can achieve the same result as with `docker-compose`. 

I can make such that the directory where we clone the notebooks are `rw` for the user `jovyan`.

**Comment by KrisThielemans** [comment]
some information on the set-up.

- it uses [KubeSpawner](https://jupyterhub-kubespawner.readthedocs.io/en/latest/)
- Information on configuration of JupyterHub:
https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-environment.html

**Comment by KrisThielemans** [comment]
Suggestion was to use [nbgitpuller](https://jupyterhub.github.io/nbgitpuller/), as suggested by the [JupyterHub doc](https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-environment.html#using-nbgitpuller-to-synchronize-a-folder) to get and sync the notebooks.

NBgitpuller syncs from github using the following strategy: https://jupyterhub.github.io/nbgitpuller/topic/automatic-merging.html.

Given our problems with notebooks and conflicts, even with nbstripout, I'm not sure if this will work. @paskino, we will have to be careful with this.

An alternative is to just copy `/opt/SIRF-Exercises`, which is possible via a `poststart` hook, see https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-environment.html#about-user-storage-and-adding-files-to-it

**Comment by paskino** [comment]
I tried plotting and it worked

**Comment by paskino** [comment]
A possible solution to the `LD_LIBRARY_PATH` is adding it in the system [/etc/environment](https://github.com/jupyterhub/jupyterhub/issues/2630#issuecomment-839826001)

Another option is to install in `/opt/pyvenv` (in the conda environment). However, conda does not set `LD_LIBRARY_PATH` but uses `RPATH`, I believe.

**Comment by KrisThielemans** [comment]
you can set env variables for conda environments, [see here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#setting-environment-variables). However, I'm not sure if kubespawner actually activates the env. (I guess so, as you can run `sirf`)



> However, conda does not set `LD_LIBRARY_PATH` but uses `RPATH`, I believe.

It uses `RPATH` when you build executables/libraries. This has nothing to do with us at the moment.

**Comment by paskino** [comment]
I believe SIRF compiles python packages with swig and installs them in the python module directory so they are found. CIL instead doesn't do that and our (little) C++ library needs to be found.

**Comment by KrisThielemans** [comment]
> I believe SIRF compiles python packages with swig and installs them in the python module directory so they are found. CIL instead doesn't do that and our (little) C++ library needs to be found.

This confuses me a bit. 
- `swig` doesn't compile anything at all. It just creates a C++ file. We tell CMake to then compile, see e.g. [here](https://github.com/SyneRBI/SIRF/blob/843eb25760ae8e1e15bc816748d8b80d9c34f7d2/src/xSTIR/pSTIR/CMakeLists.txt#L30-L39).
- `LD_LIBRARY_PATH` applies for run-time stuff, not compilation stuff. I see that CIL has a number of shared libraries, so their location has indeed to be in the `LD_LIBRARY_PATH` (just like the ITK, ISMRMRD and Gadgetron library)

> A possible solution to the `LD_LIBRARY_PATH` is adding it in the system [/etc/environment](https://github.com/jupyterhub/jupyterhub/issues/2630#issuecomment-839826001)

I think far preferable would be to add a file `/etc/ld.conf.d/sirif-cil.conf` with the install location. See e.g.
https://unix.stackexchange.com/questions/425251/using-ldconfig-and-ld-so-conf-versus-ld-library-path

**Comment by KrisThielemans** [comment]
what about the radical solution to install in `/usr/local`? Stuff like path and `LD_LIBRARY_PATH` is no longer needed...

**Comment by paskino** [comment]
OK, it seems like this https://github.com/paskino/SIRF-SuperBuild/releases/tag/jupyterhub_v0.0.0 is the first jupyterhub config that works. We'll build on that.

**Comment by KrisThielemans** [comment]
This is currently still in the above fork. We will merge this for the next version.
