### ISSUE TITLE
docker (and others): Gadgetron or ISRMRD can link with hdf5 but not find it at run-time

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#573]
In our docker, we have 2 hdf5 libraries: one installed with `apt` and the other one with `conda`. They don't have the same version of course.

During build time, it uses the one from `conda` (possibly because it is more recent). However, this is not in our `LD_LIBRARY_PATH`.
Therefore gadgetron fails. See https://github.com/SyneRBI/SIRF-SuperBuild/pull/566#issuecomment-859718511.

I would have thought that a `conda activate base` would add `/opt/pyvenv/lib`, but it doesn't. Maybe I do that wrong?

In any case, it seems to imply that we need to add the location of the `hdf5` library to `LD_LIBRARY_PATH` somehow.

**Comment by KrisThielemans** [comment]
I suggest for 3.1 to just fix this on docker. Best way could be to follow https://stackoverflow.com/a/46833531/15030207.

**Comment by KrisThielemans** [comment]
By the way, it seems that `conda` fixes this for python, but it cannot know about executables that we compiled of course so cannot fix those. It doesn't like changing the `LD_LIBRARY_PATH` as it might have undesirable consequences, see e.g. https://docs.conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#id18

For our case, there could be a conflict with the `libhdf.so.103` installed by `conda`, and the `libhdf.s0.100` installed by `apt`, i.e. if setting `LD_LIBRARY_PATH` to include conda's `libhdf5`, `apt` utilities might fail. However, that seems quite unlikely.

**Comment by KrisThielemans** [comment]
Note that `conda` installed `hdf5` due to https://github.com/SyneRBI/SIRF-SuperBuild/blob/f0ed06b00cb7a14628bf0776e723dfe07433bcf0/docker/requirements_conda_forge.txt#L1
This is why we hadn't seen this earlier

**Comment by KrisThielemans** [comment]
reopening as I've fixed it on Docker, but it is a problem that needs a better fix later

**Comment by KrisThielemans** [comment]
It isn't fixed on `docker` as the tests fail of course (as there's C++ tests there as well).

Best to add to `LD_LIBRARY_PATH` in `.bashrc`?

**Comment by paskino** [comment]
> Note that `conda` installed `hdf5` due to
> 
> https://github.com/SyneRBI/SIRF-SuperBuild/blob/f0ed06b00cb7a14628bf0776e723dfe07433bcf0/docker/requirements_conda_forge.txt#L1
> 
> 
> This is why we hadn't seen this earlier

It's more likely this
https://github.com/SyneRBI/SIRF-SuperBuild/blob/f0ed06b00cb7a14628bf0776e723dfe07433bcf0/docker/requirements.txt#L7

**Comment by KrisThielemans** [comment]
Actually, when I re-run this now on a freshly built machine, the `LD_LIBRARY_PATH` is set ok (prepended) and it works. Looks like we won't need #586.

I'll update Travis in a few minutes and we'll see I guess.

**Comment by KrisThielemans** [comment]
so indeed. `docker` is now fine. I'll leave the issue open as it still applies for others.

**Comment by KrisThielemans** [comment]
@paskino, I think this is obsolete. Feel free to close.
