### ISSUE TITLE
docker: need to freeze SIRF-SuperBuild tag

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#589]
currently we're building `master`. Needs to be fixed for a particular version possibly? I think it will be alright for the `release` versions on DockerHub, but if people build it themselves, they will currently get the latest, which would be surprising.

**Comment by KrisThielemans** [comment]
https://github.com/SyneRBI/SIRF-SuperBuild/blob/86038b3f64c3c3c7836fbaf36a1a82b78f6e00f9/docker/user_sirf-ubuntu.sh#L6

**Comment by KrisThielemans** [comment]
potentially update the `README` to pull the `release`

**Comment by KrisThielemans** [comment]
can we default to using the `tag/hash` of the currently checked-out `SIRF-SuperBuild`?

Better to use `COPY`

**Comment by paskino** [comment]
Can't use copy to copy parent directory.

```bash 

Step 8/10 : COPY .. /edo
COPY failed: Forbidden path outside the build context: .. ()
```

**Comment by paskino** [comment]
I tried with this 
https://docs.docker.com/engine/reference/commandline/build/#build-with-path

```
$ docker build ..
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /mnt/data/CCPi/code/CIL/Dockerfile: no such file or directory
```

**Comment by paskino** [comment]
Apparently with the above command docker cannot find the `Dockerfile` which can be fixed by `-f <path_to>/Dockerfile`. Then it's the previous error, though.

**Comment by KrisThielemans** [comment]
It could be done via the build context, setting it to `..` presumably.

Note that the `COPY` strategy is a bit dangerous as we don't know what the user has in their ``SIRF-SuperBuild` (e.g. large overhead when they're using an in-source build).

**Comment by KrisThielemans** [comment]
I'm preparing a PR that allows you to specify `TAG` and `URL` instead. Not so good, but I think I know how to do it (and safer)
