### ISSUE TITLE
docker: will need scripts for release images

### ISSUE THREAD

**Issue by DANAJK** [SyneRBI/SIRF-SuperBuild#592]
Currently the sirf-compose-* and yml scripts do not provide for the release-service image?

**Comment by KrisThielemans** [comment]
The question is how to do this without a ton of duplication.

This could possibly be resolved by using env variables for the names. Maybe by using `.env`. See e.g. https://docs.docker.com/compose/env-file/

e.g.
```
./sirf-compile --env-file release
```
would have to set the new `SIRF_SB_TAG` presumably, see #593 

Also gets tricky with terminology (anyone confused between release/latest/devel?)

**Comment by DANAJK** [comment]
At this stage, it might be safer to just have a little more duplication.
