### ISSUE TITLE
docker: entrypoint fails if group exists

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#606]
Found by @mastergari

`./sirf-compose` tries to find the group of the current user, and create a group in the docker image accordingly. However, when that group already exists, subsequent `adduser` fails:
```
“Creating sirfuser:501:20
addgroup: The GID `20' is already in use.
adduser: The group `sirfuser' does not exist.
addgroup: The user `sirfuser' does not exist.
Updating file ownership for /home/sirfuser
chown: invalid user: ‘sirfuser:sirfuser’
Switching to sirfuser and executing /usr/local/bin/service.sh
error: failed switching to "sirfuser": unable to find user sirfuser: no matching entries in passwd file”
```

**Comment by KrisThielemans** [comment]
The problem is in the following lines
https://github.com/SyneRBI/SIRF-SuperBuild/blob/3c01b373ebb2f7968f93a0ca101c8503f2140f50/docker/entrypoint.sh#L28-L34
The `adduser` command should use the `--gid` option as opposed to `--ingroup`, as the groupname would have failed.

**Comment by KrisThielemans** [comment]
A possibly work-around for an existing image could be to edit `sirf-compose` and say
```
cd "$(dirname $0)"
export GROUP_ID=10000 # some non-existent group  number
export USER_ID=$(id -u)
docker-compose -f docker-compose.yml -f docker-compose.nix.yml "$@"
```
or equivalently edit https://github.com/SyneRBI/SIRF-SuperBuild/blob/3c01b373ebb2f7968f93a0ca101c8503f2140f50/docker/docker-compose.yml#L9

**Comment by KrisThielemans** [comment]
Better would be to pull the PR:
```
cd /wherever/SIRF-SuperBuild/docker
git remote add kris-fork git@github.com:KrisThielemans/SIRF-SuperBuild.git
git fetch kris-fork
git checkout docker_group_fix
./sirf-compose-server down 
./sirf-compose-server build sirf
docker image prune # get rid of previous image
./sirf-compose-server up -d sirf
```

**Comment by KrisThielemans** [comment]
@mastergari let us know if you try either of those.

**Comment by KrisThielemans** [comment]
This works for me, but of course I never had the problem.

**Comment by mastergari** [comment]
@KrisThielemans I am able to access localhost:9999 after editing sirf-comopose with your above commands. I was unable to pull the PR which failed at "git fetch kris-fork" due to insufficient access rights:

      Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts.
      git@github.com: Permission denied (publickey).
      fatal: Could not read from remote repository.
      
      Please make sure you have the correct access rights
      and the repository exists.

I had no problems setting up docker on my linux machine. Thank you for the assistance!

**Comment by KrisThielemans** [comment]
oops.
```
git remote add kris-fork https://github.com/KrisThielemans/SIRF-SuperBuild.git
```
Anyway. We'll probably merge this tomorrow. Thanks for letting us know!
