### ISSUE TITLE
find_package(Cython) fails to find cython3

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#624]
On my Ubuntu 20.04 (under WSL2, but I can't see how that matters) I have `cython3` (I could install `cython` which will give me a Python2 version), but surely don't want to).

Building with `BUILD_CIL_LITE=ON` gives
```
-- SuperBuild -     astra-python-wrapper => Requires astra-toolbox,
-- SuperBuild -       astra-toolbox => Requires Boost[INCLUDED],
-- SuperBuild -       astra-toolbox[OK]
CMake Error at SuperBuild/External_astra-toolbox.cmake:32 (message):
  astra-toolkit binding to Python depends on Cython
Call Stack (most recent call first):
  CMake/ExternalProjectDependency.cmake:593 (include)
  SuperBuild/External_astra-python-wrapper.cmake:29 (ExternalProject_Include_Dependencies)
  CMake/ExternalProjectDependency.cmake:593 (include)
  SuperBuild/External_CIL-ASTRA.cmake:28 (ExternalProject_Include_Dependencies)
  CMake/ExternalProjectDependency.cmake:593 (include)
  CMake/ExternalProjectDependency.cmake:639 (ExternalProject_Include_Dependencies)
  SuperBuild.cmake:331 (ExternalProject_Include_Dependencies)
  CMakeLists.txt:43 (include)
```
I can set `CYTHON_EXECUTABLE` to `/usr/bin/cython3`
https://github.com/SyneRBI/SIRF-SuperBuild/blob/053bfabcdfd0967873aaaf68252e7e0ef497cc26/CMake/FindCython.cmake#L11

However, this is probably unexpected for most people. Possibly even worse, it seems that if you have `cython` and its Python2, it'll find that one.

I see that this file comes from https://github.com/symengine/symengine.py/blob/master/cmake/FindCython.cmake which has moved on a bit. However, that one will first find `cython`, which again seems dangerous.

**Comment by paskino** [comment]
Let's check if on Ubuntu 22.04 there is still `cython` and `cython3`.

**Comment by paskino** [comment]
`cython3` is not installed but `python` is not installed by default. 
I suggest we install [`python-is-python3`](https://packages.ubuntu.com/jammy/python-is-python3)

**Comment by KrisThielemans** [comment]
In Ubuntu 22.04, we have `python3` and (confusingly) `cython`. These are found fine. So let's leave this.
