### ISSUE TITLE
Bump parallelproj version to 0.8

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#631]
This requires https://github.com/UCL/STIR/pull/973 first

**Comment by KrisThielemans** [comment]
I think it is required. @gschramm is 0.8 backwards compatible with the existing code in STIR?

**Comment by gschramm** [comment]
No unfortunately not. 0.8 does not work with the old STIR code and the new STIR code does not work with <=0.7.
Mea culpa for not increasing the major version number. I promise to do that from now on if I make changes that break backward compatibility.
