### ISSUE TITLE
Set minimum ISMRMRD required version to 1.4.2

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#635]
Once https://github.com/SyneRBI/SIRF/pull/936 is merged, during the build of SIRF we will require ISMRMRD version 1.4.2.

**Comment by KrisThielemans** [comment]
should be 1.7.0 when building `siemens_to_ismrmrd`.

We need to set `ISMRMRD_REQUIRED_VERSION` which amazingly we don't do.

In addition, we set `DEFAULT_NIFTYREG_REQUIRED_VERSION` but this should be called `NIFTYREG_REQUIRED_VERSION`. We don't set `STIR_REQUIRED_VERSION` (currently 4.1.0), not `parallelproj_REQUIRED_VERSION` (should be 0.8). Probably a bunch of others as well but let's start here.

**Comment by paskino** [comment]
This is a SIRF issue, isn't it?

**Comment by evgueni-ovtchinnikov** [comment]
Does not look so to me - I understand ISMRMRD is installed based on `SIRF-SuperBuild/version.config.cmake`.

**Comment by paskino** [comment]
No, I agree. 

Do we want to check the ISMRMRD version? I am confused on how we would do that.

Possibly a check [here](https://github.com/SyneRBI/SIRF-SuperBuild/blob/91f4f72d19ec68e1efa127e5fc916a531ec2b416/SuperBuild/External_ISMRMRD.cmake#L58) just before `ExternalProject_Add`.

**Comment by paskino** [comment]
But also, how do we check. If we pass a version string that CMake can compare, it's all fine, but what if the `ISMRMRD_TAG` is a commit tag? How do we get to the version?

`git describe` could possibly work with some effort, but this will need to happen in the `CONFIG_COMMAND` phase.

Any suggestion?

**Comment by evgueni-ovtchinnikov** [comment]
> How do we get to the version?

perhaps we could run `ismrmrd_info >ismrmrd_info.txt` and fish the version from `ismrmrd_info.txt`?

**Comment by paskino** [comment]
This would require that we first build. 

I think this check is going to be too complicated. I guess we need to document it. 
Possibly I will create a table with minimum required version for the readme.

**Comment by evgueni-ovtchinnikov** [comment]
> This would require that we first build.

ISMRMRD must be built before SIRF, and we already use `ismrmrd_generate_cartesian_shepp_logan` when building SIRF anyway

**Comment by KrisThielemans** [comment]
In my opinion, this is only required when `USE_SYSTEM_ISMRMRD=ON`. We can assume that if we set the version/tag/commit ourselves, that we know what we're doing :-).

We check version here
https://github.com/SyneRBI/SIRF-SuperBuild/blob/b3b9e0fa25c9ca0d0e7d830b838598f1ec80e32f/SuperBuild/External_ISMRMRD.cmake#L85
except that `ISMRMRD_REQUIRED_VERSION` is not set. So, I think that in `version_config.cmake` we simply do
```cmake
  if (build_Siemens_to_ismrmrd)
    ISMRMRD_REQUIRED_VERSION=1.7
  else()
   ISMRMRD_REQUIRED_VERSION=1.4.1 # or whatever SIRF needs
  endif()
```

Similar for STIR etc
