### ISSUE TITLE
CIL framework test failures?

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#640]
I've just built from scratch on the latest VM, `DEVEL_BUILD=on`, `BUILD_CIL=ON` etc, using gcc9. Everything SIRF-side works fine but I get lots of CIL failures in the tests, such as
```
/home/sirfuser/devel/build-gcc9/INSTALL/python/cil/framework/framework.py:2918: DeprecationWarning: Direct invocation is deprecated and will be removed in following version. Use allocate from AcquisitionGeometry instead
  DeprecationWarning)
Shape mismatch got (2, 3) expected (3, 5, 2, 10)
.Allocate complex array to a complex geometry
Cannot cast array data from dtype('complex128') to dtype('float32') according to the rule 'same_kind'
....../home/sirfuser/devel/build-gcc9/INSTALL/python/cil/framework/framework.py:2814: DeprecationWarning: Direct invocation is deprecated and will be removed in following version. Use allocate from ImageGeometry instead
  DeprecationWarning)
Shape mismatch (2, 3) (2, 3, 2)
.Allocate complex array to a complex geometry
Cannot cast array data from dtype('complex128') to dtype('float32') according to the rule 'same_kind'
...Allocate complex array to a complex geometry
Cannot cast array data from dtype('complex128') to dtype('float32') according to the rule 'same_kind'
..test axpby
```
This is on CIL `origin/master`.

Weird thing though is that our latest GHA workflow run tests CIL `master` (same commit) as well and it goes through.

@paskino @gfardell @epapoutsellis  any ideas? Maybe this should be raised on the BIL GitHub, but possibly I've made a mistake somewhere.
@paskino @gfardell @epapoutsellis

**Comment by epapoutsellis** [comment]
Wow really strange. Do you know which test failed? Is it a pure CIL test? or a test about CIL_and_SIRF?

**Comment by KrisThielemans** [comment]
`test_DataContainer.py`. Some that work: `test_algorithms.py`, `test_AcquisitionGeometry`, `test_Operator.py` (in fact all others run by the SuperBuild).

This is Ubuntu 18.04, python 3.6.9, numpy 1.19.5

**Comment by paskino** [comment]
The `same_kind` error should come from [using `axpby` on complex data](https://github.com/TomographicImaging/CIL/blob/0a434c8b8086d2b759b4f3d66f7cc42e8099dfe9/Wrappers/Python/cil/framework/framework.py#L2598-L2601). However, our 7 unittests on `axpby` do not use complex data.

```python
        if nda.dtype != dtype:
            nda = nda.astype(dtype, casting='same_kind')
        if ndb.dtype != dtype:
            ndb = ndb.astype(dtype, casting='same_kind')
```

I do not understand which one is failing in your attached output. The fact that GHA works and the VM not is suspicious.

**Comment by paskino** [comment]
@KrisThielemans is this still relevant?

**Comment by KrisThielemans** [comment]
As we are testing on GHA now with gcc 9, and everything is fine, this problem must have disappeared on its own. phew!
