### ISSUE TITLE
Ubuntu 21.10 gadgetron build gtest missing dependecy

### ISSUE THREAD

**Issue by samdporter** [SyneRBI/SIRF-SuperBuild#647]
Running Ubuntu 21.10 issue building gadgetron
cmake uses wrong version of libgtest-dev and can't build because of missing dependency on libgmock-dev

**Comment by KrisThielemans** [comment]
As far as I recall, this means we need to add `libgmock-dev` to our list of apt packages.

The underlying reason for the conflict is that new GTest has a CMake Config file, while the old one doesn't. When building GTest ourselves, we build an old version, and set `GTEST_ROOT`, but when a new version is present, CMake will prefer to find the Config version (i.e. the new one).

**Comment by paskino** [comment]
The package `libgmock-dev` [exists ](https://packages.ubuntu.com/search?keywords=libgmock-dev&searchon=names&suite=focal&section=all)in Ubuntu20.04 but [not ](https://packages.ubuntu.com/search?suite=bionic&searchon=names&keywords=libgmock-dev)on 18.04

**Comment by KrisThielemans** [comment]
@paskino to add `libgmock-dev` if it exists (as it isn't in 18.04) (in both `docker` and VM)

**Comment by KrisThielemans** [comment]
https://unix.stackexchange.com/questions/199633/how-to-check-from-bash-if-package-exists-in-debian/199634 implies you could test with
```sh
if apt-cache show libgmock-dev >& /dev/null`; then
  apt install  libgmock-dev
fi
```

**Comment by KrisThielemans** [comment]
We also need to update our usage of `GTEST_ROOT` to use `GTest_DIR` when upgrading GTest. Using the usual `GTest_CMAKE_FLAGS` here as well would help, and address #126.

**Comment by paskino** [comment]
Looks like `libgtest-dev` isn't installed in the docker build!
