### ISSUE TITLE
upgrade CIL

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#658]
Our Actions are occasionally failing due to the numerical problems resolved in https://github.com/TomographicImaging/CIL/pull/1160. We need to update to a CIL version that includes that commit

**Comment by paskino** [comment]
current installed version is[ 21.3.1](https://github.com/SyneRBI/SIRF-SuperBuild/blob/89aaac4d0b45029c30953ac954f190d9c1bdb36c/version_config.cmake#L154) which doesn't have that fix.

@gfardell @epapoutsellis We are planning to release soon. How soon, I don't know. Should we go now for current master?
