### ISSUE TITLE
boost vs CMake version

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#667]
We install a very recent boost now, but default to CMake 3.13. This has the potential to create trouble as CMake will not know about Boost component dependencies, see [here](https://github.com/Kitware/CMake/blob/de52151359f404ee8acb25f29de1f7fc3b1fa9ca/Modules/FindBoost.cmake#L1013).

I think we have to update our CMake version in docker/VM. However, I also wonder if we really have to install bleeding edge Boost. @paskino did you have a reason not to use 1.72 (which I saw flying by).

**Comment by KrisThielemans** [comment]
CMake 3.10 supports up to Boost 1.66 https://github.com/Kitware/CMake/blob/7746fdb2fe0177341aadeafec2ae73aa08ddfaf6/Modules/FindBoost.cmake#L800

Looks like Boost 1.72 is supported from CMake 3.16.2 https://github.com/Kitware/CMake/commit/e51232b739b3eeae642be8a7e89079f7c2e8c1b2

If Boost 1.72 is fine, I'd be fine with requiring 3.16.2 in the SuperBuild. Probably lots of other bug fixes along the way anyway. It means Ubuntu 18.04 users need to get a more recent CMake, but they should anyway...

**Comment by paskino** [comment]
Maybe https://github.com/SyneRBI/SIRF-SuperBuild/issues/666 is linked to this? Although I don't see how GHA get away with it!

> @paskino did you have a reason not to use 1.72 (which I saw flying by).

I suppose my thinking was in view of supporting Gadgetron master.

**Comment by KrisThielemans** [comment]
If boost 1.72 works, please use that for now, with associated CMake 3.16.2. Once 3.2 is out, we can revisit.

**Comment by paskino** [comment]
Actually https://github.com/SyneRBI/SIRF/issues/1069 requires CMake 3.17

**Comment by KrisThielemans** [comment]
Sure, but I consider that a bug which should be fixed. Sorry

Kris
________________________________

**Comment by paskino** [comment]
Sure, but I want to get a working image for the hackathon on Thursday. They require CIL and SIRF master and it doesn't build! 
Once I get that, I'll tackle the issue!

**Comment by paskino** [comment]
OK, it built.

This means that we need to update the minimum required version of CMake here
https://github.com/SyneRBI/SIRF-SuperBuild/blob/422dd237d958c012afb168de99be50dbbc639550/CMakeLists.txt#L21-L25

**Comment by KrisThielemans** [comment]
Sorry. As 20.04 comes with Clarke 3.16.3, I'd rather not require 3.17 yet. I'm on with using 3.1u in docker and the VM though.

**Comment by paskino** [comment]
I perfectly agree! I now managed to create an image with SIRF and CIL master, which I'll test tomorrow.

Then I'll change the CMake version to 3.16.3 and do a version check for https://github.com/SyneRBI/SIRF/issues/1069

**Comment by paskino** [comment]
Why is this still open? Both #668 and https://github.com/SyneRBI/SIRF/issues/1069 are fixed now.

**Comment by KrisThielemans** [comment]
Did you updated CMake minimum requirements as mentioned above? If so, feel free to close
