### ISSUE TITLE
docker build fails on SB master

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#684]
```
[ 99%] Performing install step for 'SIRF'
...
Install the project...
-- Install configuration: "Release"
-- Installing: /opt/SIRF-SuperBuild/INSTALL/include/sirf/common/version.h
CMake Error at cmake_install.cmake:61 (file):
  file cannot create directory: /sirf.  Maybe need administrative privileges.


Makefile:138: recipe for target 'install' failed
make[3]: *** [install] Error 1
CMakeFiles/SIRF.dir/build.make:93: recipe for target 'builds/SIRF/stamp/SIRF-install' failed
make[2]: *** [builds/SIRF/stamp/SIRF-install] Error 2
CMakeFiles/Makefile2:192: recipe for target 'CMakeFiles/SIRF.dir/all' failed
make[1]: *** [CMakeFiles/SIRF.dir/all] Error 2
Makefile:114: recipe for target 'all' failed
make: *** [all] Error 2
```

It suggests that it is trying to install in the wrong directory:

```
CMake Error at cmake_install.cmake:61 (file):
  file cannot create directory: /sirf.  Maybe need administrative privileges.
```

`cmake_install.cmake` at line 61 has indeed 
```cmake
file(INSTALL DESTINATION "/sirf" TYPE FILE FILES "/opt/SIRF-SuperBuild/builds/SIRF/build/cmake/config.py")
```

However the CMake cache seems to be configured correctly

```
CMAKE_INSTALL_PREFIX             /opt/SIRF-SuperBuild/INSTALL
 CMAKE_LIBRARY_PATH               /opt/SIRF-SuperBuild/INSTALL/lib
 CMAKE_PREFIX_PATH                /opt/SIRF-SuperBuild/INSTALL
```

**Comment by KrisThielemans** [comment]
it finds python 2.7.17. I'd have hoped they first attempt to find Python3, but maybe not. I'd have to check, but either set 
```
Python_EXECUTABLE=`which python3`
```
or make sure you're in a `venv`

**Comment by paskino** [comment]
As a matter of fact, I normally add `-DPYVER=3` to my CMake command...

**Comment by paskino** [comment]
Also I think we should definitely drop Python2 and exit with a `FATAL_ERROR` here https://github.com/SyneRBI/SIRF/blob/b8a7d15f72e5ad70d4ee68252e88d83480469231/CMakeLists.txt#L134

**Comment by KrisThielemans** [comment]
> Also I think we should definitely drop Python2 and exit with a `FATAL_ERROR` here https://github.com/SyneRBI/SIRF/blob/b8a7d15f72e5ad70d4ee68252e88d83480469231/CMakeLists.txt#L134

no, we should just require Python version 3. Then CMake does that check for us, and it probably avoids this nonsense where it fails because it finds python2 first. Feel free to create an issue for SIRF v3.3

**Comment by KrisThielemans** [comment]
> As a matter of fact, I normally add `-DPYVER=3` to my CMake command to avoid this kind of problems.

what about defaulting `PYVER` to 3 now? I think that'll reduce a lot of confusion.
