### ISSUE TITLE
vagrant up failed

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF-SuperBuild#686]
@paskino Tried to follow the instructions at https://github.com/SyneRBI/SIRF-SuperBuild/tree/master/VirtualBox/vagrant.

After a long while vagrant up failed with this error:
```
    default:   Attempting uninstall: pexpect
    default:     Found existing installation: pexpect 4.2.1
    default: ERROR: Cannot uninstall 'pexpect'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
    default: An error occurred in /home/sirfuser/devel/SyneRBI_VM/scripts/INSTALL_python_packages.sh at line 70. Current working-dir: /home/sirfuser/devel/SyneRBI_VM
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what went wrong.
```

**Comment by paskino** [comment]
Strangely I see that you have `/home/sirfuser/devel/SyneRBI_VM/scripts/INSTALL_python_packages.sh` while this directory should not be there in a freshly created VM.

The `SyneRBI_VM` repo shouldn't be cloned. I suspect vagrant started an old VM. 

Try to modify the VM name here
https://github.com/SyneRBI/SIRF-SuperBuild/blob/0e7ff7759a0c693f4392a3f2a0f2caea44a74cf8/VirtualBox/vagrant/Vagrantfile#L77

and retry. This should create a new VM.

**Comment by paskino** [comment]
I now notice that you have tried this from the `SyneRBI_VM` repo, https://github.com/SyneRBI/SyneRBI_VM/issues/199. Yes, that's now obsolete and all the VM stuff is in the SuperBuild. 

So, please try again starting from the Vagrant file in the SuperBuild.

**Comment by evgueni-ovtchinnikov** [comment]
@paskino thanks!

Still few errors:
```
    default: W: http://archive.ubuntu.com/ubuntu/pool/main/l/lapack/liblapack3_3.7.1-4ubuntu1_amd64.deb: Automatically disabled Acquire::http::Pipeline-Depth due to incorrect response from server/proxy. (man 5 apt.conf)
    default: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/l/lapack/liblapack3_3.7.1-4ubuntu1_amd64.deb  400  Bad Request [IP: 185.125.190.39 80]
    default: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
and I had to comment out line 37 in Vagrantfile (port 9001 was claimed to be listened to by some other device).

But the VM is up and running!

I am a bit confused though - I understand we no longer clone `SyneRBI_VM`, do we? But then where do I edit `VM_version.txt` and other stuff from Sect. 5 of the Release Checklist before `vagrant up`? Do I do it on VM, including `vagrant up`?

Also, where do I do the suggested `apt-get update` - on VM? And which command am I supposed to use with `--fix-missing` -  would it be `vagrant up` on VM?

I feel I am more of a nuisance rather than help, sorry!

**Comment by KrisThielemans** [comment]
first error seems to imply we need to do `apt update` in our `Vagrantfile`, but we already do at https://github.com/SyneRBI/SIRF-SuperBuild/blob/7dd71b73a6470663533bc039117389d5982d25e2/VirtualBox/scripts/bootstrap_ubuntu.sh#L19
I wonder therefore if this wasn't a timeout

Second error is probably because there was another VM already running.

`VM_version.txt` now is https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/VirtualBox/VM_version.txt. the checklist will need changing.

**Comment by paskino** [comment]
@evgueni-ovtchinnikov can you confirm the errors were due to timeout?

**Comment by evgueni-ovtchinnikov** [comment]
not sure about timeout, but definitely no other VMs were running

**Comment by paskino** [comment]
closing as it worked
