### ISSUE TITLE
Zenodo release update error

### ISSUE THREAD

**Issue by DANAJK** [SyneRBI/SIRF-SuperBuild#690]
Zenodo has not updated for two releases. Error message is

"errors": "{'metadata': {'related_identifiers': {2: {'relation': [u'Not a valid choice.']}}}}"

**Comment by KrisThielemans** [comment]
See also https://github.com/SyneRBI/SIRF/issues/1086 for discussion on how to resolve

**Comment by DANAJK** [comment]
Fixed
