### ISSUE TITLE
tagged 3.2.0 VM builds from not existing branch

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#700]
Unfortunately I left in this line

https://github.com/SyneRBI/SIRF-SuperBuild/blob/6b07c1790d7a8c6eebbb58b6d435027cf6930808/VirtualBox/scripts/bootstrap_ubuntu.sh#L82

**Comment by KrisThielemans** [comment]
I recommend doing v3.2.1, certainly if anything else crops up.
