### ISSUE TITLE
docker core build failure on build_gadgetron-ubuntu.sh (on Travis)

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#705]
building of `core` fails at https://github.com/SyneRBI/SIRF-SuperBuild/blob/775d4a18bccc0bc67b194622eb976acd61620a8f/docker/build_gadgetron-ubuntu.sh#L29

https://app.travis-ci.com/github/SyneRBI/SIRF-SuperBuild/jobs/564233945#L3031
```
The following additional packages will be installed:
  googletest libpython-stdlib libpython2.7-minimal libpython2.7-stdlib python
  python-minimal python2.7 python2.7-minimal
Suggested packages:
  python-doc python-tk python2.7-doc binfmt-support
The following NEW packages will be installed:
  googletest libgtest-dev libpython-stdlib libpython2.7-minimal
  libpython2.7-stdlib python python-minimal python2.7 python2.7-minimal
0 upgraded, 9 newly installed, 0 to remove and 0 not upgraded.
Need to get 4,618 kB of archives.
After this operation, 24.4 MB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.
```

No idea why

**Comment by KrisThielemans** [comment]
I tried to build `core` locally, which worked without problems. I really don't know what is going on.

**Comment by paskino** [comment]
Wonderful!

**Comment by paskino** [comment]
As of #732 docker builds on travis are [green](https://app.travis-ci.com/github/SyneRBI/SIRF-SuperBuild/builds/252980447).

@KrisThielemans, shall we close this?

**Comment by KrisThielemans** [comment]
Amazing! Party-time!

Sure I'll close this
