### ISSUE TITLE
Docker: setting LD_LIBRARY_PATH breaks library resolution

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#709]
We are struggling to resolve the appropriate libraries at runtime, see #573 or https://github.com/SyneRBI/SIRF/issues/1094 and all devel builds are failing.

The current solution for docker is to add to `LD_LIBRARY_PATH` in `.bashrc`
https://github.com/SyneRBI/SIRF-SuperBuild/blob/1024422a85c54d480d1a33a441c13fd9f862c2c1/docker/.bashrc#L27-L29

However, during a docker build I stumbled upon a huge problem: having set `LD_LIBRARY_PATH` makes so that some libraries that are in the conda install are picked before the system ones, so that basic tools, like `mv`, don't work and the build fails. BTW @KrisThielemans had already [suspected](https://github.com/SyneRBI/SIRF-SuperBuild/issues/573#issuecomment-860175624) this!

I was thinking to use `RPATH` for Gadgetron. It seems they already use the [`INSTALL_RPATH`](https://github.com/gadgetron/gadgetron/blob/9e733b193c60df78575577a237d1c237f0eb3826/CMakeLists.txt#L109)

```cmake
set(CMAKE_INSTALL_RPATH ".:${CMAKE_INSTALL_PREFIX}/lib")
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
```

But they don't use the [`BUILD_RPATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_RPATH.html).

**Comment by paskino** [comment]
To me it looks like that this is a problem only if `miniconda` is selected at 
https://github.com/SyneRBI/SIRF-SuperBuild/blob/1024422a85c54d480d1a33a441c13fd9f862c2c1/docker/Dockerfile#L75

because also might install several other _system_ libraries.

**Comment by KrisThielemans** [comment]
I believe this has been resolved. Maybe some stuff to do for jupyterhub. If so, @paskino reassign to 3.4

**Comment by KrisThielemans** [comment]
@paskino I think this needs to be closed.
