### ISSUE TITLE
our boost version is too old for Ubuntu 22.04

### ISSUE THREAD

**Issue by samdporter** [SyneRBI/SIRF-SuperBuild#725]
compiling with `USE_SYSTEM_BOOST=OFF` gave a thread-related error (sorry, didn't record it). After switching to  using the system boost (1.74), everything works fine.

**Comment by KrisThielemans** [comment]
This is probably due to gcc-11. https://packages.ubuntu.com/jammy/gcc. Updating `version_config.cmake` should be harmless. Let's do it for `APPLE` as well.

**Comment by KrisThielemans** [comment]
Boost is being updated in #438. Potentially we do this separately (although that PR looks ready)

**Comment by paskino** [comment]
With #787 the base Ubuntu is 22.04 and the Boost version has increased to 1.78.0. Will this fix the problem?

**Comment by KrisThielemans** [comment]
should do
