### ISSUE TITLE
docker core fails to build

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#727]
https://app.travis-ci.com/github/SyneRBI/SIRF-SuperBuild/jobs/572981957#L801-L804
```
Step 6/33 : RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
 ---> Running in d325922b9b53
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
The command '/bin/sh -c apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub' returned a non-zero code: 255
```
The GPU-core does build on Travis (amazing!).

We shouldn't need to have to do NVidia stuff on the non-GPU docker really, but if it's easier, then fine for me.

**Comment by paskino** [comment]
I guess the difference is the base image `ubuntu:18.04` does not have any of gnupg, gnupg2 and gnupg1 which is apparently required to update the key.
