### ISSUE TITLE
Building with USE_ROOT=ON fails when package "uuid-dev" is not installed

### ISSUE THREAD

**Issue by NicoleJurjew** [SyneRBI/SIRF-SuperBuild#728]
I tried to build SIRF with "USE_ROOT=ON" but got the following error messages/log files:

![image](https://user-images.githubusercontent.com/86268422/173584746-f9d84348-d72d-4106-90b9-5d4b9949a62f.png)

![image](https://user-images.githubusercontent.com/86268422/173584830-c5759f02-ed53-42cc-999d-b37d2f351693.png)

After I installed "uuid-dev" and started my build from scratch, I was able to compile without an error.

I'm running on Ubuntu 20.04

**Comment by KrisThielemans** [comment]
@paskino I suggest to add it to our apt list. it's a common and small package anyway.
