### ISSUE TITLE
VM: update_VM.sh fails on GENERATE_SIMULATED_TEST_DATA 

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#745]
Once #743 is fixed, I continued the build but didn't complete. 

Got the following error

```
Scanning dependencies of target MR_PROCESS_TESTDATA
                 from /home/sirfuser/devel/buildVM/sources/SIRF/src/xGadgetron/cGadgetron/tests/mrtest_auxiliary_funs.h:32,
                 from /home/sirfuser/devel/buildVM/sources/SIRF/src/xGadgetron/cGadgetron/tests/mrtests_prep_testdata.cpp:30:
/home/sirfuser/devel/buildVM/sources/SIRF/src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_image_wrap.h: In destructor ‘sirf::ImageWrap::~ImageWrap()’
:
                                                                         ^
/home/sirfuser/devel/buildVM/sources/SIRF/src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_image_wrap.h:268:4: note: in expansion of macro ‘IMAGE_PROCmpl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >'
  what():  unrecognised option '-w'
Child aborted
src/xGadgetron/cGadgetron/tests/CMakeFiles/GENERATE_SIMULATED_TESTDATA.dir/build.make:77: recipe for target 'src/xGadgetron/cGadgetron/tests/CMakeFiles/GENERATE_SIMULATED_TESTDATA' failed
```
Notice that something crashes.

**Comment by paskino** [comment]
Is it a Boost error? A version problem? On the VM we are using system Boost
https://github.com/SyneRBI/SIRF-SuperBuild/blob/d9de45ba5163eb175d6bb8cd37a2031755fd4d26/VirtualBox/scripts/UPDATE.sh#L194-L198

**Comment by KrisThielemans** [comment]
This is a bit confusing. The error is related to `boost::program_options::unknown_option` which seems to imply it's calling an executable that uses `program_options`. However, the lines around/above it are SIRF lines. Is this output of a parallel build?

I suspect that the SIRF lines around it are a red-herring and that it's really related to the call to `ismrmrd_generate_cartesian_shepp_logan`
https://github.com/SyneRBI/SIRF/blob/23a7e7ade525be7f1b84e63f194a0331962699a3/src/xGadgetron/cGadgetron/tests/CMakeLists.txt#L147
which seems to imply it's running on old version of this executable. (Are you upgrading an existing VM?)

**Comment by paskino** [comment]
Yes, I'm trying to update the VM and got to fix a million lines. 

Is it a parallel build? I do not think so as I used `update_VM.sh -j1`, unless `-j1` is treated as a single option, hence discarded!

I think the failing line might be the one you point out.

Shouldn't the `update_VM.sh` also update the `ismrmrd_generate_cartesian_shepp_logan` executable?

**Comment by KrisThielemans** [comment]
>  I'm trying to update the VM

to be 100% clear. you have an existing VM, and you try to update it. Correct?

> got to fix a million lines.

for an existing VM, you will really need the `-s` option (once)

> I used `update_VM.sh -j1`, unless `-j1` is treated as a single option, hence discarded!

I haven't checked bash `getopts` but I do think you need a space
https://github.com/SyneRBI/SIRF-SuperBuild/blob/225b7fa20bfaac05e28a7ff586be99c0d3dd164c/VirtualBox/scripts/UPDATE.sh#L51
Of course, it should have exited with a wrong option
https://github.com/SyneRBI/SIRF-SuperBuild/blob/225b7fa20bfaac05e28a7ff586be99c0d3dd164c/VirtualBox/scripts/UPDATE.sh#L60-L61


> Shouldn't the `update_VM.sh` also update the `ismrmrd_generate_cartesian_shepp_logan` executable?

sure, but did it? `git status` in the `sources/ISMRMRD` and all that.

**Comment by paskino** [comment]
I have removed the ISMRMRD build directory before checking, so I can't check that now, but I will do it later on another VM.
Currently I have ISMRMRD v1.7.0 as espected in SIRF-SuperBuild 3.2.0.
 
The error is as you imagined

```
enerating Cartesian Shepp Logan Phantom!!!
Acceleration: 1
cd /home/sirfuser/devel/buildVM/builds/SIRF/build/src/xGadgetron/cGadgetron/tests/data/examples/MR && /usr/local/bin/cmake -E env LD_LIBRARY_PATH=/home/sirfuser/devel/install/lib:/home/sirfuser/devel/install/lib:/home/sirfuser/devel/install/lib64:: /home/sirfuser/devel/install/bin/ismrmrd_generate_cartesian_shepp_logan -w 64 -a 2 -o testdata_tmp_2.h5
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >'
  what():  unrecognised option '-w'
```

**Comment by paskino** [comment]
now, `ismrmrd_generate_cartesian_shepp_logan` may be the old one?

```
sirfuser@vagrant:~/devel/buildVM$ find . | grep ismrmrd_generate_cartesian_shepp_logan
```

return nothing. It doesn't seem to have been built?

**Comment by KrisThielemans** [comment]
you could repeat this in `~/devel`. Then do an `ls -l`

it's hard to know what your status is though If you have an existing VM where you messed about a lot. For instance, you wrote
> I have removed the ISMRMRD build directory before checking


I'd recommend starting from scratch really.

**Comment by paskino** [comment]
OK, here's what I did:

```
rm -rf buildVM
rm -rf install

./SIRF-SuperBuild/VirtualBox/scripts/update_VM.sh -j 4
```

It ends with a CMake error that `ismrmrd_generate_cartesian_shepp_logan` cannot be found.

As a matter of fact the executable should be built by ISMRMRD if HDF5, Boost and FFTW3 are [found](
https://github.com/ismrmrd/ismrmrd/blob/c86c89cfcee43e4ce1c146f6e4817dc2e06b2e63/utilities/CMakeLists.txt#L19-L50)
but they are not

```
- Could NOT find Boost (missing: random) (found suitable version "1.65.1", minimum required is "1.43")
-- FFTW3 UNIX libraries: /usr/lib/x86_64-linux-gnu/libfftw3.so/usr/lib/x86_64-linux-gnu/libfftw3f.so
-- Found FFTW3: /usr/lib/x86_64-linux-gnu/libfftw3f.so  
FFTW3 or Boost NOT Found, cannot build utilities
```
But in the 3.1.0 VM Boost random is missing.

**Comment by KrisThielemans** [comment]
did you use `-s`? It should install all required boost libraries

**Comment by paskino** [comment]
Indeed I did not!

**Comment by KrisThielemans** [comment]
you're going to hit some of the other issues I created then...

**Comment by paskino** [comment]
Somewhat linked is https://github.com/SyneRBI/SyneRBI_VM/pull/201

**Comment by KrisThielemans** [comment]
This is now obsolete (after #755 and possibly #758 )
