### ISSUE TITLE
docker: llvmlite install failure

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#761]
Same error as what was fixed by @paskino https://github.com/SyneRBI/SIRF-SuperBuild/issues/742#issuecomment-1210753672

See https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for more info, saying that you have to be lucky enough to have a prebuilt binary wheel (presumably the one that @paskino used is no longer available), or install full LLVM (which seems a bit overkill), or use conda...

@lauramurgatroyd @gfardell any ideas?

**Comment by gfardell** [comment]
I'm afraid not, I'm not sure why numba is being installed with pip and not conda to begin with so it would take me some time to figure out how it all works.  Can this wait until Edo gets back?

**Comment by KrisThielemans** [comment]
> I'm not sure why numba is being installed with pip and not conda

Either pip or conda (I can't remember what way around) wanted to upgrade some stuff from the other but couldn't, so in the end it became "mostly pip".

> it would take me some time to figure out how it all works

It doesn't look too complicated at the moment.
https://github.com/SyneRBI/SIRF-SuperBuild/blob/6d27730aa44b891b4df7381827459aa5a2307968/docker/user_python-ubuntu.sh#L54-L65

we are using conda for python (https://github.com/SyneRBI/SIRF-SuperBuild/runs/7947210121?check_suite_focus=true#step:7:3591).  Miniconda3 py39_4.12.0

I guess we could try to remove the numba version restriction

https://github.com/SyneRBI/SIRF-SuperBuild/blob/6d27730aa44b891b4df7381827459aa5a2307968/docker/requirements.txt#L15-L17

> Can this wait until Edo gets back?

That's tough one :-) I've been pushing (and Edo has been working) to get this release out for a long time. I thought that after this weekend, we'd be there. Oh well.

**Comment by KrisThielemans** [comment]
There is no problem when creating a new VM, which uses almost the same scripts. The difference is that it uses the python3.6 and downloads most recent pip, while docker uses conda python 3.9.

I think we're just out-of-luck regarding which binaries they provide. The docker (i.e. conda setup) indeed [builds the llvmlite 0.33 wheel](https://github.com/SyneRBI/SIRF-SuperBuild/runs/7947210121?check_suite_focus=true#step:7:5447), which then fails.

Checking prebuilt wheels at https://pypi.org/project/llvmlite/0.35.0/#files and https://pypi.org/project/llvmlite/0.33.0/#files, there are no python 3.9 versions around. However, most recent numba 0.56 needs llvmlite 0.39 (see here](https://numba.readthedocs.io/en/stable/user/installing.html#version-support-information), which has some python 3.9 "manylinux" stuff at https://pypi.org/project/llvmlite/0.39.0/#files.

If that doesn't work, I see a few solutions:
- installing numba via conda, which is what Edo tried to avoid for at least some stuff (as pip install of packages failed, possibly because they were trying to upgrade conda packages). 
- install LLVM anyway (increasing size dramatically presumably)
- use conda Python 3.8 presumably

sigh. There has to be a better way to let pip and conda play together.


I note that when building a new VM, it first installs llvmlite-0.33.0 numba-0.50.1 (due to the `docker/requirements.txt`), and then uninstalls that and installs llvmlite-0.36.0 numba-0.53.1 (due to the [SIRF-Exercises/requirements.txt](https://github.com/SyneRBI/SIRF-Exercises/blob/5a68a66fc3743cbd5fe31502c145060ab7d03a11/requirements.txt#L8-L9). So @paskino's version-trick wouldn't work anyway.

**Comment by KrisThielemans** [comment]
Prebuilt llvmlite is now available for the configurations that we need. @paskino must have been unlucky.

Of course, this is all quite unstable. As the numba team recommends conda, presumably it will be better to try and remove pip as much as possible in the future.
