### ISSUE TITLE
GUI backend for matplotlib needs to be installed.

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF-SuperBuild#764]
On VM 3.3.0-pre2, one gets warnings:
```
Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
```
and plots are not shown.

We should be able to fix it by adding `tkinter` in `docker/requirements`.

**Comment by KrisThielemans** [comment]
on second thought, better to add it after this
https://github.com/SyneRBI/SIRF-SuperBuild/blob/844ca0f18ed334d9af91a8b18ad4390ddad81c91/VirtualBox/scripts/INSTALL_python_packages.sh#L76-L78
such that it is VM specific. Can you do a PR for that (just `pip install tkinter` I guess)

**Comment by KrisThielemans** [comment]
There's no pip package for tkinter. It seems to need `sudo apt-get install python3-tk`. (Adds 5.5MB). I'll do this on the VM only as I'm not sure on docker how to handle this with conda etc (and have no time to find out)
