### ISSUE TITLE
error in make Sirf-superBuild

### ISSUE THREAD

**Issue by Pierre-1618** [SyneRBI/SIRF-SuperBuild#773]
Hello all,
I'm trying to install  SIRF with CMake version 3.21.3 and Python 3.10.6 with the commands:
`$mkdir ~/devel       
$export PATH=/home/mamo/bin/cmake/bin:$PATH
$set path =  /home/mamo/bin/cmake/bin $path
$cd ~/devel
$git clone https://github.com/SyneRBI/SIRF-SuperBuild.git     
$mkdir ~/devel/build
$cd ~/devel/build
$export CC=gcc7
$export CXX=g++7             # or clang (same problem)
$cmake ../SIRF-SuperBuild                  
$make -j3  `

and the command `make -j3`

give me this error :
`[ 84%] Completed 'ITK'
[ 85%] Built target ITK
Makefile:100: recipe for target 'all' failed
make: *** [all] Error 2`

I already try to specify something for python (even if I don't have Matlab) and used another computer and a different N=3, but I got the same problem.
Do you have any ideas what the problem can be and how to solve it?
Pierre
[error2.txt](https://github.com/SyneRBI/SIRF-SuperBuild/files/9819019/error2.txt)
[error.txt](https://github.com/SyneRBI/SIRF-SuperBuild/files/9819020/error.txt)

**Comment by KrisThielemans** [comment]
hi, it could help others if you document how this was resolve. as you wish
