### ISSUE TITLE
docker on Travis errors related to gpg

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#790]
while building docker core
```
E: Problem executing scripts DPkg::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.LYf3xxs07e/gpg.1.sh --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
gpg: requesting key from 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub'
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.LYf3xxs07e/S.dirmngr' failed: End of file
gpg: WARNING: unable to fetch URI https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub: No dirmngr
The command '/bin/sh -c bash update_nvidia_keys.sh && rm update_nvidia_keys.sh' returned a non-zero code: 2
```
full log https://app.travis-ci.com/github/SyneRBI/SIRF-SuperBuild/jobs/593499693#L1033 (edit: corrected the line number)

**Comment by KrisThielemans** [comment]
https://unix.stackexchange.com/questions/401547/gpg-keyserver-receive-failed-no-dirmngr seems to stay we might need to install `dirmngr`.

I don't understand why the docker build on Travis would be different from the one on GHA of course. That seems to break all rules. Maybe the 22.04 image got updated. oh well

**Comment by paskino** [comment]
It seems to do the stats of usage.

**Comment by KrisThielemans** [comment]
@paskino, I had fixed that already. The new log that showed the above error is https://app.travis-ci.com/github/SyneRBI/SIRF-SuperBuild/jobs/593533864

**Comment by KrisThielemans** [comment]
I could reproduce this on my old VM. However, then I found https://unix.stackexchange.com/a/717121, which says that it could be because the `docker` version is too old. Upgrading Travis to run docker on focal fixed it!

**Comment by KrisThielemans** [comment]
Documented in https://github.com/SyneRBI/SIRF-SuperBuild/commit/413be42c8d4b4ab2fbb502ff1a2fd51b4b61d953

**Comment by KrisThielemans** [comment]
@paskino All Travis docker builds are green! https://app.travis-ci.com/github/SyneRBI/SIRF-SuperBuild/builds/259816193 congrats
