### ISSUE TITLE
Typo in parallelproj source code

### ISSUE THREAD

**Issue by samdporter** [SyneRBI/SIRF-SuperBuild#805]
/devel/build/sources/parallelproj/c/include/parallelproj_c.h

line 284
typo:           `short n_tofbins;`
correction:  `short n_tofbins,`

I didn't know exactly where this came from in SIRF/STIR so didn't do a PR

Tested after this correction and SIRF builds fine on master branch

**Comment by KrisThielemans** [comment]
This was fixed in `parallelproj` 1.0.1. STIR now requires that. I think we can just close this here.
