### ISSUE TITLE
Docker: service.sh expects the cloned notebooks in the wrong directory

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#816]
SIRF-Exercises are cloned in `/opt` by [default](https://github.com/SyneRBI/SIRF-SuperBuild/blob/a0d01deac13c16330327c315e0353581b4e56b5d/docker/user_service-ubuntu.sh#L4), but `service.sh` expects them in `/devel`

https://github.com/SyneRBI/SIRF-SuperBuild/blob/a0d01deac13c16330327c315e0353581b4e56b5d/docker/service.sh#L40

**Comment by KrisThielemans** [comment]
this needs some checking. Remember that `/devel` is mounted to the user's local directory (when using our scripts anyway), so the script might be copying some stuff cloned notebooks there. That'd be confusing but not necessarily incorrect. The intention was that people would end up with notebooks etc that survived the docker container.

**Comment by paskino** [comment]
Thanks. I'm trying to use the docker container with the service, and I'm struggling. Some time ago I managed to run it with `docker` rather than with `docker compose`.  My current command is 

```
docker run -p 9002:9002 -p 9999:8888 synerbi/sirf:service
```

Clearly, I am missing mounting local directory as directory on the container.
https://github.com/SyneRBI/SIRF-SuperBuild/blob/a0d01deac13c16330327c315e0353581b4e56b5d/docker/docker-compose.yml#L31-L32

I followed this guide to install `docker compose` on my machine, https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-22-04

However, using the `sirf-compose-service-gpu` command fails with `./sirf-compose: line 5: docker-compose: command not found`

**Comment by paskino** [comment]
Just to be more explicit, using `docker run -p 9002:9002 -p 9999:8888 synerbi/sirf:service`  the container exists immediately

```
docker container ls -a
CONTAINER ID   IMAGE                  COMMAND   CREATED          STATUS                      PORTS     NAMES
afa5052bf529   synerbi/sirf:service   "bash"    22 seconds ago   Exited (0) 22 seconds ago             zen_buck
```
Instead of running the `entrypoint.sh` it runs bash not interactively... 
I thought that instead of running

**Comment by KrisThielemans** [comment]
> However, using the `sirf-compose-service-gpu` command fails with `./sirf-compose: line 5: docker-compose: command not found`

ah well. must be something wrong in their install instructions then. Is it executable? Correct directory etc? Alternatively, there's also https://docs.docker.com/compose/install/linux/

**Comment by KrisThielemans** [comment]
> Instead of running the `entrypoint.sh` it runs bash not interactively...

 I don't think I've ever used `docker run` on a `service` image. I guess you could experiment with the `--entrypoint` option, but that shouldn't be necessary AFAIK.  So I don't know really. (Are you sure it's running a service image? I recall some problems because all of them were called `sirf`).

**Comment by paskino** [comment]
It seems that we are missing the command `up` here.

https://github.com/SyneRBI/SIRF-SuperBuild/blob/a0d01deac13c16330327c315e0353581b4e56b5d/docker/sirf-compose#L5

Still there are problems due to 
https://github.com/SyneRBI/SIRF-SuperBuild/blob/a0d01deac13c16330327c315e0353581b4e56b5d/docker/docker-compose.yml#L44-L49

I guess they should be removed as Gadgetron is built within the image?

**Comment by KrisThielemans** [comment]
> It seems that we are missing the command `up` here.
> 
> https://github.com/SyneRBI/SIRF-SuperBuild/blob/a0d01deac13c16330327c315e0353581b4e56b5d/docker/sirf-compose#L5

No, our doc says that the user has to type `up` herself (or `build`), as in
```
./sirf-compose-server up -d sirf
```
> Still there are problems due to
> ...
> I guess they should be removed as Gadgetron is built within the image?

This creates a gadgetron service using their image. Those lines are not used, unless you'd do
```
./sirf-compose-server up -d gadgetron
```
or something like that. This was a brief attempt to see if we could use their image, but it was never pursued. AFAIK, these lines are harmless, although confusing. (By the way, it looks like the gadgetron docker image doesn't get updated very regularly https://hub.docker.com/u/gadgetron/#!)

**Comment by paskino** [comment]
Thanks! I had just figured it out. Unfortunately `-d` yields `unknown shorthand flag: 'd' in -d`. This is possibly due to the fact that we are using a new docker compose version?

**Comment by KrisThielemans** [comment]
no idea. that used to work

**Comment by KrisThielemans** [comment]
I don't see anything here that we can/need to fix at the moment, so will shift the milestone. @paskino feel free to disagree and switch it back.

**Comment by casperdcl** [comment]
- the `ENTRYPOINT` does the copying from `/opt` (read-only) to `/devel` (writable mount)
- `./sirf-compose` uses `docker-compose` which might need changing to `docker compose` (` ` not `-`) on some systems

anyway all of this will be nuked by #718 :)
