### ISSUE TITLE
jupyter missing in latest docker pre-built service image

### ISSUE THREAD

**Issue by mlewis1973** [SyneRBI/SIRF-SuperBuild#827]
1) docker pull synerbi/sirf:service
2) ./sirf-compose-server up -d sirf
3) docker logs -f sirf

same errors on Ubuntu 20.04 and 2 separate Macs with different macOS
building image also fails

/opt/SIRF-SuperBuild ~
start gadgetron
cp: cannot stat './INSTALL/share/gadgetron/config/gadgetron.xml.example': No such file or directory
make sure the SIRF-Exercises and CIL-Demos are in the expected location (/devel in the container)
Creating link to SIRF-contrib
start jupyter
~
/usr/local/bin/service.sh: line 61: jupyter: command not found

**Comment by KrisThielemans** [comment]
> cp: cannot stat './INSTALL/share/gadgetron/config/gadgetron.xml.example': No such file or directory

I think that be ignored. It's a bit confusing at the moment as we're close to release a new version with recent gadgetron, and take into account that that file no longer exists. 

> /usr/local/bin/service.sh: line 61: jupyter: command not found

that cannot be ignored of course! I suppose that you could try and install it via docker/requirements-service.yml, but it's going to be a bit tricky to get to the command line. Our README claims the following should work
```
docker exec -w /devel -ti sirf /bin/bash
```
> building image also fails

can you elaborate please?

**Comment by mlewis1973** [comment]
The user 'sirfuser' in synerbi/sirf:service lacks 
/opt/conda/bin 
in PATH
I added it to .bashrc for that user and then ran
docker stop sirf ; docker start sirf
(apt-get update; apt install vim to get oldschool vi to edit .bashrc)

that brought jupyter up successfully..... the default password 'virtual' did not work, 
so I used the token that I could see with
docker logs -f sirf

I opened the Introductory jupyter notebook.
Gadgetron cells appear to work.

brainweb seems to be missing from the image though (pip install brainweb)
CIL also not found (manual fix not as apparent)




to elaborate on when I try to just build the image, I get the same result as in
[SyneRBI/SIRF-SuperBuild] docker: fix mamba libarchive.so.13 not found (Issue #826)

**Comment by KrisThielemans** [comment]
hmm. lots of things wrong here. weird. It is a while ago that we build that (on Travis).

I note that we used the SIRF-SuperBuild with `BUILD_CIL=OFF` and there is no `conda` install of it. (You can use `conda` to install it as per its instructions).

All missing dependencies would be fixed when building from current SIRF-SuperBuild `master` I believe, but not the `path` issue. I've triggered a build on Travis which might push an updated version. 

To work-around #826, I suppose you could replace use of `mamba` with `conda`, although that's going to be somewhat tricky due to #664.

**Comment by mlewis1973** [comment]
is there an older tagger image on docker hub that is more 'robust' for doing the tutorials?
I pulled the v3.1.0 service image and cloned v3.1.0 SIRF-SuperBuild, but docker/sirf-compose-server still wants to build from scratch rather than use the equivalent tagged image

or should we just go the VM route?

**Comment by KrisThielemans** [comment]
Somewhat surprised that it rebuilds, but 3.1 is rather old. I haven't tried this in a while though.

The VM will work.

You could also try GitHub CodeSpaces as now documented in the SIRF-Exercirses (but it seems you need GitHub Pro, e.g. educational account).

Sorry.

Hopefully we can fix this soon (during the week 😃)

**Comment by KrisThielemans** [comment]
I've pushed new versions of the docker images to the hub [via Travis](https://app.travis-ci.com/github/SyneRBI/SIRF-SuperBuild/builds/265200903).

Maybe this will be fixed, although we didn't do any specific modifications for it, so probably not!

@casperdcl would you be able to check/address this?
