### ISSUE TITLE
CCPi regularisation fails test

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF-SuperBuild#832]
CCPi regularisation toolkit builds but unit tests fail with messages as
https://github.com/SyneRBI/SIRF-SuperBuild/pull/829#issuecomment-1643646935
or
```
File "/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/CCPi-Regularisation-Toolkit/test/test_run_test.py", line 5, in <module>
    from ccpi.filters.regularisers import ROF_TV, FGP_TV, PD_TV, SB_TV, TGV, LLT_ROF, FGP_dTV, NDF, Diff4th
  File "/home/runner/install/python/ccpi/filters/regularisers.py", line 5, in <module>
    from ccpi.filters.cpu_regularisers import TV_ROF_CPU, TV_FGP_CPU, TV_PD_CPU, TV_SB_CPU, dTV_FGP_CPU, TNV_CPU, NDF_CPU, Diff4th_CPU, TGV_CPU, LLT_ROF_CPU, PATCHSEL_CPU, NLTV_CPU
ImportError: /home/runner/install/python/ccpi/filters/cpu_regularisers.cpython-310-x86_64-linux-gnu.so: undefined symbol: _Z14SB_TV_CPU_mainPfS_S_fifiiii
```

- [x] depends on https://github.com/vais-ral/CCPi-Regularisation-Toolkit/issues/178
- [x] depends on https://github.com/TomographicImaging/CCPi-Regularisation-Toolkit/pull/183
- [ ] depends on CIL v24.0.0 https://github.com/TomographicImaging/CIL/pull/1778

**Comment by paskino** [comment]
We should reinstate https://github.com/SyneRBI/SIRF-SuperBuild/pull/829/commits/90faebc93f6a67ae19840a344f2cc15a64b563f7 and https://github.com/SyneRBI/SIRF-SuperBuild/pull/829/commits/6e0b7e37b57ddf9269af0defc9afa0dc52b07f78

**Comment by paskino** [comment]
After #829 the ccpi-regularisation is not built as CIL dependency

**Comment by casperdcl** [comment]
@paskino I guess you'll push a new toolkit release?

**Comment by paskino** [comment]
Can we just use a different commit hash

**Comment by KrisThielemans** [comment]
fine for me
