### ISSUE TITLE
SuperBuild failures on VM 3.4

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF-SuperBuild#841]
SuperBuild fails on VM 3.4 with the following output:
```
[ 68%] Performing update step for 'Gadgetron'
[ 68%] No patch step for 'Gadgetron'
[ 68%] Performing configure step for 'Gadgetron'
loading initial cache file /home/sirfuser/devel/buildVM/builds/Gadgetron/tmp/Gadgetron-cache-Release.cmake
-- Looking for packages in : /home/sirfuser/devel/install
64bit system is found
OpenMP multithreading enabled
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:141 (find_package):
  Could not find a package configuration file provided by "boost_coroutine"
  (requested version 1.74.0) with any of the following names:
    boost_coroutineConfig.cmake
    boost_coroutine-config.cmake
  Add the installation prefix of "boost_coroutine" to CMAKE_PREFIX_PATH or
  set "boost_coroutine_DIR" to a directory containing one of the above files.
  If "boost_coroutine" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:258 (boost_find_component)
  /usr/local/share/cmake-3.21/Modules/FindBoost.cmake:594 (find_package)
  CMakeLists.txt:209 (find_package)
-- Configuring incomplete, errors occurred!
See also "/home/sirfuser/devel/buildVM/builds/Gadgetron/build/CMakeFiles/CMakeOutput.log".
See also "/home/sirfuser/devel/buildVM/builds/Gadgetron/build/CMakeFiles/CMakeError.log".
make[2]: *** [CMakeFiles/Gadgetron.dir/build.make:104: builds/Gadgetron/stamp/Gadgetron-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:506: CMakeFiles/Gadgetron.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
```
(Gadgetron being on commit `0670db847aca8df629b2005c1b23512dda84f175`).

As @paskino pointed out, one needs to `apt install libboost-coroutine-dev libboost-context-dev` to fix the above build error, and I have found that to make the SuperBuild build successfully, one needs to `apt install` also `boost-python-dev` and `golang`.

**Comment by KrisThielemans** [comment]
Is this updating an existing VM, it creating a new one?

If the former, you need to use the -s switch to install new system stuff.

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans  I presume `-s` is for `update_VM.sh`? But I did not want to update the VM (fearing it would take long),  I just wanted to use the recent Gadgetron, so I simply edited `version_confug.cmake` and did `ccmake` and `make` in `~/devel/buildVM`.

If that was a completely wrong way to update Gadgetron, I am going to close this issue.

**Comment by evgueni-ovtchinnikov** [comment]
Forgot to mention - I updated `SIRF-SuperBuild` first, of course.

**Comment by KrisThielemans** [comment]
if you don't want to update everything, but only the required packages, I recommend to use https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/VirtualBox/scripts/INSTALL_prerequisites_with_apt-get.sh. You could also use https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/VirtualBox/scripts/INSTALL_python_packages.sh or the lines in there.

**Comment by paskino** [comment]
The new gadgetron depends on _at least_ some boost libraries that are not installed on the 3.4 VM. Therefore, you wouldn't be able to build the latest Gadgetron this way.

**Comment by paskino** [comment]
The new gadgetron depends on _at least_ some boost libraries that are not installed on the 3.4 VM. Therefore, you wouldn't be able to build the latest Gadgetron this way.
