### ISSUE TITLE
bump gadgetron

### ISSUE THREAD

**Issue by casperdcl** [SyneRBI/SIRF-SuperBuild#851]
To fix gadgetron-python support

> we need https://github.com/gadgetron/gadgetron/pull/1229. This is now merged. Pretty much nothing has happened in Gadgetron except the very last commit, so I suggest trying to set  `Gadgetron_TAG=6202fb7352a14fb82817b57a97d928c988eb0f4b` (version of Oct 13, 2023).
> However, *before* that merge, they merged https://github.com/gadgetron/gadgetron/pull/1225, which set ismrmrd=1.13.7, and siemens_to_ismrmrd=1.2.11, so we will need to update those versions as well (`DEFAULT_*_TAG`, not `REQUIRED`, as this is only for building them, no SIRF).

-- @KrisThielemans in https://github.com/SyneRBI/SIRF-SuperBuild/pull/718#issuecomment-1876579808

so:

```
Gadgetron_TAG=6202fb7352a14fb82817b57a97d928c988eb0f4b
ISMRMRD_TAG=v1.13.7
siemens_to_ismrmrd_TAG=v1.2.11
```

**Comment by casperdcl** [comment]
Also, in https://github.com/SyneRBI/SIRF-SuperBuild/blob/929fa6052d14d2c5f99d8917f5cd0b27c13bece8/version_config.cmake#L202 (`DEVEL_BUILD=ON`) why not this?

```diff
- set(DEFAULT_siemens_to_ismrmrd_TAG b87759e49e53dab4939147eb52b7a0e6465f3d04)
+ set(DEFAULT_siemens_to_ismrmrd_TAG origin/master)
```

**Comment by KrisThielemans** [comment]
Thanks for assigning to me, but I'm afraid I'd rather have someone else taking care of it... @paskino @evgueni-ovtchinnikov ?

**Comment by casperdcl** [comment]
> We have had a lot of trouble trying to track the Gadgetron guys in the past. If we do this, we'd also have to track ISMRMRD master etc. There's no reason for us to be so bleeding edge on that front, so I'd prefer to keep DEFAULT and DEVEL tags the same.

we already track `master` on everything else

https://github.com/SyneRBI/SIRF-SuperBuild/blob/929fa6052d14d2c5f99d8917f5cd0b27c13bece8/version_config.cmake#L195-L216

**Comment by KrisThielemans** [comment]
should be master of SIRF and STIR only, as those are the only ones we have under control. Or in fact, maybe want to do SIRF only, for STIR have a fixed (but recent) commit.
