### ISSUE TITLE
parallelproj build failed on OSX due to omp.h not found

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#870]
@francescaleek has a failure funding `omp.h` when building parallelproj, but not any other project (whcih is a bit weird, but could be because STIR does not require OpenMP). The parallelproj CMake settings look like this:
![image](https://github.com/SyneRBI/SIRF-SuperBuild/assets/6362141/3f73b1c0-7847-4eb1-8047-152883ec248b)

We currently do
https://github.com/SyneRBI/SIRF-SuperBuild/blob/e43323735471174437666bf4134721e1413529ad/SuperBuild/External_parallelproj.cmake#L43-L48
similarly for STIR
https://github.com/SyneRBI/SIRF-SuperBuild/blob/e43323735471174437666bf4134721e1413529ad/SuperBuild/External_STIR.cmake#L105-L106
and overall (as [`mark_as_superbuild` should transport those to the subprojects](https://cmake-artichoke.readthedocs.io/en/latest/ExternalProjectDependency.html))
https://github.com/SyneRBI/SIRF-SuperBuild/blob/e43323735471174437666bf4134721e1413529ad/SuperBuild.cmake#L225-L231

I note we set `OPENMP_INCLUDES`, but https://cmake.org/cmake/help/latest/module/FindOpenMP.html says we should use `OpenMP_CXX_INCLUDE_DIR` (and some for C)

Note that none of this is necessary on Linux/g++ but @rijobro put it in for MacOS. Possibly `FindOpenMP.cmake` has moved on.

**Comment by KrisThielemans** [comment]
@francescaleek could you check if STIR is actually built with OpenMP (i.e. open the `builds/STIR/build` build dir in the CMake GUI and see if `STIR_OPENMP` is `ON`), to understand if this is a generic problem, or specific to parallelproj,

**Comment by francescaleek** [comment]
Yes, `STIR_ENABLE_OPENMP` is `ON`

**Comment by KrisThielemans** [comment]
@francescaleek confirms NiftyReg fails with the same problem. STIR not, but likely it is going ahead without OpenMP

**Comment by KrisThielemans** [comment]
Related: #502

**Comment by KrisThielemans** [comment]
There's an additional problem with NiftyReg: https://github.com/KCL-BMEIS/niftyreg/issues/109. NiftyReg PR at https://github.com/KCL-BMEIS/niftyreg/pull/110
