### ISSUE TITLE
Another Docker README question http or https for localhost?

### ISSUE THREAD

**Issue by DANAJK** [SyneRBI/SIRF-SuperBuild#889]
Seems to be that I have to use http and not https for the localhost link. Am I doing things correctly?

**Comment by KrisThielemans** [comment]
Confirmed on Windows with WSL. Pointing to `https://localhost:9999/` gives "This connection is not secure". Using "http://localhost:9999/" works

**Comment by casperdcl** [comment]
yes should be `http`.
