### ISSUE TITLE
re-enable recent CMake

### ISSUE THREAD

**Issue by KrisThielemans** [SyneRBI/SIRF-SuperBuild#916]
We currently use APT CMake, but it's too old for good CUDA support. We neeed at least 3.23.0.
commented out lines:
https://github.com/SyneRBI/SIRF-SuperBuild/blob/d725d08f3d18308f4f14ab1b249e70b2acdbdc67/docker/build_essential-ubuntu.sh#L24-L27

**Comment by casperdcl** [comment]
Fixed by #917
