### ISSUE TITLE
Number of users

### ISSUE THREAD

**Issue by casperdcl** [SyneRBI/SIRF-SuperBuild#93]
- [x] count superbuild clones properly (see [github-stats#viewing][gh-stats])
- [x] count VM downloads (via drupal)
- [x] count docker pulls (![](https://img.shields.io/docker/pulls/ccppetmr/sirf.svg))
  - [x] TODO: subtract travis' docker pulls (or just estimate this from [github-stats][gh-stats]'s decrements)

[gh-stats]: https://github.com/CCPPETMR/github-stats#viewing

## Ambitious

- [x] write a script (probably part of [github-stats][gh-stats]) to collate the following:
  + [x] https://github.com/CCPPETMR/github-stats/blob/CCPPETMR/SIRF-SuperBuild/CCPPETMR_SIRF_SuperBuild.json
  + [x] https://hub.docker.com/v2/repositories/ccppetmr/sirf/
  + [ ] drupal download counts? Could you have a JSON API for this @paskino 
  + [x] travis' docker pulls?

## original description

We'd like to estimate the number of users. Sum number of:

+ (SuperBuild clones) - (travis non-docker jobs) - 2*(travis docker jobs) - (a little extra for devs locally cloning?)
+ (docker pulls) - (travis docker jobs)
+ VM binary downloads

The main problem I see is (SuperBuild clones) is only accessible at https://github.com/CCPPETMR/SIRF-SuperBuild/graphs/traffic if you are logged in to github (not publicly accessible via a JSON API) so I can't get that data to generate a badge.

So... would it be OK to generate that data ourselves using `cmake`? By that I mean something like

```cmake
file(DOWNLOAD "http://caspersci.uk.to/cgi-bin/hits.cgi?q=sirf-superbuild"
  "${CMAKE_BINARY_DIR}/clones.svg")
# file(REMOVE "${CMAKE_BINARY_DIR}/clones.svg")
```

to increment our counter, and then get `.travis.yml` to call

```bash
wget https://caspersci.uk.to/cgi-bin/hits.cgi?q=sirf-superbuild-travis -o /dev/null -b
```

a few times to decrement... that way I can give you something like: ![](https://caspersci.uk.to/cgi-bin/hits.cgi?q=sirf-superbuild&m=sirf-superbuild-travis&label=installs&a=display&l=https://avatars2.githubusercontent.com/u/16674841?s=32&amp;v=4)

**Comment by casperdcl** [comment]
@KrisThielemans ?

**Comment by casperdcl** [comment]
@paskino for VM binary downloads, you may want to use something link https://stackoverflow.com/questions/21982862/how-to-count-link-clicks#21982932

**Comment by paskino** [comment]
There's a way directly in Drupal to count them.

**Comment by paskino** [comment]
Accessing the clones via the GitHub API requires, as Casper said, an authorized webapp. So it can't be a simple script. I developed an authorized webapp to query GitHub API and I may modify to get the relevant info. 

At any rate, data which can be collected is only for the last 14 days.

**Comment by paskino** [comment]
I managed to get drupal track the downloads of SIRF VM. ATM the info is not publicly available. Do we need live info?

**Comment by KrisThielemans** [comment]
no need to be live as far as I can see

**Comment by KrisThielemans** [comment]
@casperdcl I think we don't need the badge as that seems quite complicated at the moment (especially agregating it all). It'd be ok if we can keep track of that ourselves. We could then periodically update the website ourselves.

I'm not 100% sure now if we still need the `file(DOWNLOAD...)` trick. It's a bit ugly... If we do need it, it'd have to be done from the CCP website (and can then be counted by Drupal) I think.

**Comment by KrisThielemans** [comment]
@casperdcl just merged a PR to be able to count github SIRF-Superbuild clones, subtracting travis ones. Great. @paskino counts VM downloads. Great. Are we counting docker downloads?
(In principle people can get the VM via vagrant etc, but I think this is a negligable minority, and that will create a SIRF-SuperBuild clone anyway, so we should be fine).

So are we done with this?

How do we get the relevant info? (can be manual as I said)

**Comment by casperdcl** [comment]
- [x] count superbuild clones properly (see [github-stats#viewing][gh-stats])
- [x] count VM downloads (via drupal)
- [x] count docker pulls (![](https://img.shields.io/docker/pulls/ccppetmr/sirf.svg))
  - [ ] TODO: subtract travis' docker pulls (or just estimate this from [github-stats][gh-stats]'s decrements)

[gh-stats]: https://github.com/CCPPETMR/github-stats#viewing

**Comment by casperdcl** [comment]
@KrisThielemans we now have an automated badge! ![install-badge] (it's in the `README` on https://github.com/CCPPETMR/SIRF-SuperBuild). Just waiting for @paskino to implement a JSON API for the vm downloads (https://github.com/CCPPETMR/github-stats/issues/1)

[install-badge]: https://img.shields.io/badge/dynamic/json.svg?label=installs&uri=https%3A//raw.githubusercontent.com/CCPPETMR/github-stats/CCPPETMR/SIRF-SuperBuild/CCPPETMR_SIRF_SuperBuild.json&query=total&colorB=8000f0&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAD0ElEQVR4nMSXS2ic5RfGf5lL/pPMZP7JjB0ba53axkvRegGhpFaxVkqjOxetoi6UUjG4ELdVFy50I6gLtfUCFilUiwheilZXIm1FiZSCpYmYRppoUpvRJONMOpmJnOT54DBtxk4CmQPDl/d85z3vc55zeb%2BEWJr0AE8uxcFSAWwE7mwkgE7gqkYCWAGkGwkgBVQaCSACFBsJwPaXgGijAJhMAonlAvAc0OHWlv8pB8BS8hLQtFhAtaRFdD%2BodQz4BngbuEm624BZ4MYFfFwUcD0MdAGjeqKojf4Jx8B1wAhwwwI%2BLuqYegBkgePAKq2Tot9AtEln744Bay7XaS0Are4wk6uBPmCl1gkByDsGMrLx%2B1L61Q3gBeBTt7axe9I5C1LgGcjIxo/nvcC%2BhQ6J1ACwWREmlWeLfNBVeELR5x0AA/czcKXzE6SjSQV6SQbiwLdAt9bNMu5zFZ5REXoAU6F5u4TTjcgfAvI78AuwVrprge%2BB1R7Aw0Leq7VV82mgX3%2BbXAGcd1G0J0Ik18foSoVply4MFFyA64ABpSUI5HEFNndW5NEo2c9LPNQT5fkS7IxBdqDCXRUY6wpxtgKZKGS/KNH6QJTV09D3P1hzqkznvRl2b2%2Bj8P4Qr8%2BGyB6ZoXlbhGwRfjA//RXuaIKJtSFOV6DD/BwuseX%2BKE8VYHcLZJuOZ3hr1zjbDqb5%2BAK0hGFm7xTd6yMM3hNj2HQxyO88zyMfpjkwDfEoFF6bZOPdGTZvbeOfE6McWgVju3Ls2J/ioyLEm6HwTp7udWGGt8YYsn3lWSq9OXr2p%2BbPCkHZWPgAeFr0GC1PAJ%2Bokls17ez5tWz2aRi9uCnOm70reKMzwgHR/6VsrPI3yHaD3h0FtgCvyGY7cMi64DfgXSnN6Bn1/IgrrE4Vk8lfug/ix/IcPFWkmCuzB/i/WhLZrtTwGmI%2B0gv6hjwqm6%2BA260I97g7/QRwq4omkBngGgfobytAa71ZOJcrz%2B1JCEBONsMKol0tbHIEeEyMomJ%2BuXoOmHIHMO50Z4FNYgod0uFG8bQuprTYCfZ0K/JAXgU%2Bc4Dm5FKTcEDtFki/qBvUekLRJsUGmg1Jl4JfgfuAM85PoYrZBQFUy0/69D7pGEi5uyCQtGPOANyifq8ptUZxIFbZz4pWXBGG3fVaUb6DFMyomA//l/PLYaCg/AUyrmj93mmNVl8777nOWRKAavlT94L/uLCauV7v6pLFABhXf09WgboZGFsOAEG%2BR53uDzEwuhwA0HQbdOszOrzuf1LCiwRg7fedi/icfj/W6%2BjfAAAA///cZAAN8LSlZAAAAABJRU5ErkJggg%3D%3D

**Comment by casperdcl** [comment]
should be noted that every time we restart a job on `travis` (because e.g. it failed due to `apt-get` connections issues) then the counter will increment (because `travis` will have cloned the repo and then failed before we could decrement)

**Comment by casperdcl** [comment]
just noticed travis osx fails due to insecure python, vis https://travis-ci.org/CCPPETMR/SIRF-SuperBuild/jobs/348359877#L2217. Not sure if this deserves a separate issue to resolve.

```python
urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
```

**Comment by KrisThielemans** [comment]
@casperdcl this seems to be working great but the numbers are going up rather a lot. Is this realistic?

**Comment by casperdcl** [comment]
Yes, I was going to mention this. The problem is (https://github.com/CCPPETMR/SIRF-SuperBuild/issues/93#issuecomment-370016495) if travis fails before it gets to the counting code, then we have no way of knowing the travis clone should not be counted.

There's a semi-solution - github also provides "unique cloners" data (presumably based on IP addresses of cloners). If we use that instead, then we accept counting up to one extra clone per day due to travis builds (even then I should be able to negate that). It might be a better approach.

**Comment by KrisThielemans** [comment]
yes. I think it makes sense to call this "users" as opposed to downloads then. after all, if someone downloads it 5 times, we're not all that interested in knowing about this.

**Comment by casperdcl** [comment]
hopefully better now

**Comment by casperdcl** [comment]
it's displaying 707 now, but that may ne because of old overcounting. can easily add an offset, but let's see whether the number is still increasing rapidly first

**Comment by casperdcl** [comment]
you really just need to write out something like

```json
{"downloads": 20}
```

in a file `www.ccppetmr.ac.uk/.../vm.json`

Presumably easy?

**Comment by paskino** [comment]
That I could do.

**Comment by paskino** [comment]
No, I can put a Json file on the website. That drupal changes it, it is a totally different ball-game. And I've currently no clue how.

**Comment by KrisThielemans** [comment]
We won't do this. In fact, I have dropped the counters from the GHA script as well, as they created access problems.
