### ISSUE TITLE
OpenMP flags

### ISSUE THREAD

**Issue by rijobro** [SyneRBI/SIRF-SuperBuild#95]
When building STIR, the user can enable `STIR_OpenMP`, reconfigure and then if necessary, set `OpenMP_CXX_FLAGS`, `OpenMP_C_FLAGS`,  `OpenMP_CXX_LIB_NAMES` and `OpenMP_C_LIB_NAMES`. These aren't exposed in the superbuild, and so compilation fails on my machine.

Could we also enable a travis test with openMP enabled for STIR?

**Comment by KrisThielemans** [comment]
aargh. macs....

It really shouldn't be necessary to have to set these flags, [but indeed we struggled with it for STIR](https://github.com/UCL/STIR/issues/117). Have a look there. Note the end statement "CMake doesn't support OpenMP with Apple's version of clang yet." (can't remember where I found that, but I believe it was in some CMake issue).

Can you add your observations on how you did get STIR-OPENMP to work on your system (os, xcode, compiler, cmake) to [the STIR issue](https://github.com/UCL/STIR/issues/117).

In STIR, we didn't manage to get openmp on Travis yet for OSX, so no point in enabling it for SIRF.(ok, we could do it for linux).

Having said all this, it would make sense to do a find(openmp) in `SuperBuild.cmake` and use `mark_as_superbuild` on the `Openmp*` variables (should only need CXX). feel free to generate a PR for this.

**Comment by DANAJK** [comment]
Is there a work around? A super build on my Mac currently fails with the error below. In cmake-gui, the BUILD_STIR_WITH_OPENMP is not checked (so it should build?)


> CMake Error at /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
>   Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
> Call Stack (most recent call first):
>   /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
>   /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindOpenMP.cmake:451 (find_package_handle_standard_args)
>   src/CMakeLists.txt:145 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/davidatkinson/devel/build/builds/STIR/build/CMakeFiles/CMakeOutput.log".
> make[2]: *** [builds/STIR/stamp/STIR-configure] Error 1
> make[1]: *** [CMakeFiles/STIR.dir/all] Error 2
> make: *** [all] Error 2

**Comment by KrisThielemans** [comment]
sorry. this is my update. Travis OSX was down, so I thought it'd work :-;

I don't understand what's going on though. I was specifically trying to avoid this issue by NOT enabling STIR_OPENMP on OSX. Can you attach the `CMakeCache.txt` of `~/devel/build/` and `~/devel/build/builds/STIR/build/`?

As a work-around for now, you can edit your local `SIRF-SuperBuild/SuperBuild.cmake`, L116 back to
```cmake
option(BUILD_STIR_WITH_OPENMP "Build STIR with OpenMP acceleration" OFF)
```
as that worked for you before. (you would have to delete your build directory, or create a new one such that we can debug the old one)

**Comment by DANAJK** [comment]
Files attached. I note their Date Modified were from yesterday so it looks like any changes I made in cmake-gui today did not affect these files.

**Comment by DANAJK** [comment]
With the workaround applied, make now finishes, but on trying to start gadgetron:


500:~$ gadgetron

dyld: Library not loaded: @rpath/libgadgetron_gadgetbase.3.14.dylib

  Referenced from: /usr/local/bin/gadgetron

  Reason: image not found

Abort trap: 6

501:~$

**Comment by KrisThielemans** [comment]
unless you changed `CMAKE_INSTALL_PREFIX` this is another version of `gadgetron`. Try executing the one in `.../INSTALL/bin`.

we currently append our directory to the `PATH` in `env_ccppetmr.sh`. maybe that's a bit idea.

**Comment by KrisThielemans** [comment]
The SuperBuild CMake should now default to false for STIR-OPENMP for OSX. My mistake was that UNIX is also true on OSX.

By the way @DANAJK, the only way I can see that setting `BUILD_STIR_WITH_OPENMP` to OFF on your cmake-gui didn't end up in the `CMakeCache.txt` is if you forgot to press `configure` again.

Let us know about gadgetron (and if you think we should put our `INSTALL/bin` first in the path, which would prevent people using other stuff by mistake).

**Comment by KrisThielemans** [comment]
@rijobro, regarding your original observation, could you maybe check at some point what Gadgetron does for OPENMP on OSX, as we don't have that problem there.

**Comment by rijobro** [comment]
Sorry, just revisiting this and I can't remember what I need to test. On OSX, `BUILD_STIR_WITH_OPENMP` defaults to `OFF` and that works just fine.

Does that mean this issue is resolved?

**Comment by KrisThielemans** [comment]
At some point, we have to get OpenMP support on working on Macs. We might then have to pass the flags through that you mentioned in your first comment.
Let's leave this for later though, so I'll reassign to 2.1.

**Comment by KrisThielemans** [comment]
@rijobro says this should now all work with Python and C++, but not with MATLAB.

**Comment by KrisThielemans** [comment]
see also #502

**Comment by KrisThielemans** [comment]
we won't support MATLAB anymore in the future, so we close this.
